// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// InquireELWPriceRequest aliases rawapi.InquireELWPriceRequest.
type InquireELWPriceRequest = rawapi.InquireELWPriceRequest

// InquireELWPriceResponse aliases rawapi.InquireELWPriceResponse.
type InquireELWPriceResponse = rawapi.InquireELWPriceResponse

// InquireELWPriceOutput1Item aliases rawapi.InquireELWPriceOutput1Item.
type InquireELWPriceOutput1Item = rawapi.InquireELWPriceOutput1Item

// NewlyListedRequest aliases rawapi.NewlyListedRequest.
type NewlyListedRequest = rawapi.NewlyListedRequest

// NewlyListedResponse aliases rawapi.NewlyListedResponse.
type NewlyListedResponse = rawapi.NewlyListedResponse

// NewlyListedOutputItem aliases rawapi.NewlyListedOutputItem.
type NewlyListedOutputItem = rawapi.NewlyListedOutputItem

// SensitivityRequest aliases rawapi.SensitivityRequest.
type SensitivityRequest = rawapi.SensitivityRequest

// SensitivityResponse aliases rawapi.SensitivityResponse.
type SensitivityResponse = rawapi.SensitivityResponse

// SensitivityOutputItem aliases rawapi.SensitivityOutputItem.
type SensitivityOutputItem = rawapi.SensitivityOutputItem

// UdrlAssetPriceRequest aliases rawapi.UdrlAssetPriceRequest.
type UdrlAssetPriceRequest = rawapi.UdrlAssetPriceRequest

// UdrlAssetPriceResponse aliases rawapi.UdrlAssetPriceResponse.
type UdrlAssetPriceResponse = rawapi.UdrlAssetPriceResponse

// UdrlAssetPriceOutputItem aliases rawapi.UdrlAssetPriceOutputItem.
type UdrlAssetPriceOutputItem = rawapi.UdrlAssetPriceOutputItem

// CondSearchRequest aliases rawapi.CondSearchRequest.
type CondSearchRequest = rawapi.CondSearchRequest

// CondSearchResponse aliases rawapi.CondSearchResponse.
type CondSearchResponse = rawapi.CondSearchResponse

// CondSearchOutput1Item aliases rawapi.CondSearchOutput1Item.
type CondSearchOutput1Item = rawapi.CondSearchOutput1Item

// QuickChangeRequest aliases rawapi.QuickChangeRequest.
type QuickChangeRequest = rawapi.QuickChangeRequest

// QuickChangeResponse aliases rawapi.QuickChangeResponse.
type QuickChangeResponse = rawapi.QuickChangeResponse

// QuickChangeOutputItem aliases rawapi.QuickChangeOutputItem.
type QuickChangeOutputItem = rawapi.QuickChangeOutputItem

// UdrlAssetListRequest aliases rawapi.UdrlAssetListRequest.
type UdrlAssetListRequest = rawapi.UdrlAssetListRequest

// UdrlAssetListResponse aliases rawapi.UdrlAssetListResponse.
type UdrlAssetListResponse = rawapi.UdrlAssetListResponse

// UdrlAssetListOutputItem aliases rawapi.UdrlAssetListOutputItem.
type UdrlAssetListOutputItem = rawapi.UdrlAssetListOutputItem

// CompareStocksRequest aliases rawapi.CompareStocksRequest.
type CompareStocksRequest = rawapi.CompareStocksRequest

// CompareStocksResponse aliases rawapi.CompareStocksResponse.
type CompareStocksResponse = rawapi.CompareStocksResponse

// CompareStocksOutput aliases rawapi.CompareStocksOutput.
type CompareStocksOutput = rawapi.CompareStocksOutput

// LpTradeTrendRequest aliases rawapi.LpTradeTrendRequest.
type LpTradeTrendRequest = rawapi.LpTradeTrendRequest

// LpTradeTrendResponse aliases rawapi.LpTradeTrendResponse.
type LpTradeTrendResponse = rawapi.LpTradeTrendResponse

// LpTradeTrendOutput1 aliases rawapi.LpTradeTrendOutput1.
type LpTradeTrendOutput1 = rawapi.LpTradeTrendOutput1

// LpTradeTrendOutput2Item aliases rawapi.LpTradeTrendOutput2Item.
type LpTradeTrendOutput2Item = rawapi.LpTradeTrendOutput2Item

// IndicatorTrendCcnlRequest aliases rawapi.IndicatorTrendCcnlRequest.
type IndicatorTrendCcnlRequest = rawapi.IndicatorTrendCcnlRequest

// IndicatorTrendCcnlResponse aliases rawapi.IndicatorTrendCcnlResponse.
type IndicatorTrendCcnlResponse = rawapi.IndicatorTrendCcnlResponse

// IndicatorTrendCcnlOutputItem aliases rawapi.IndicatorTrendCcnlOutputItem.
type IndicatorTrendCcnlOutputItem = rawapi.IndicatorTrendCcnlOutputItem

// IndicatorTrendMinuteRequest aliases rawapi.IndicatorTrendMinuteRequest.
type IndicatorTrendMinuteRequest = rawapi.IndicatorTrendMinuteRequest

// IndicatorTrendMinuteResponse aliases rawapi.IndicatorTrendMinuteResponse.
type IndicatorTrendMinuteResponse = rawapi.IndicatorTrendMinuteResponse

// IndicatorTrendMinuteOutputItem aliases rawapi.IndicatorTrendMinuteOutputItem.
type IndicatorTrendMinuteOutputItem = rawapi.IndicatorTrendMinuteOutputItem

// IndicatorTrendDailyRequest aliases rawapi.IndicatorTrendDailyRequest.
type IndicatorTrendDailyRequest = rawapi.IndicatorTrendDailyRequest

// IndicatorTrendDailyResponse aliases rawapi.IndicatorTrendDailyResponse.
type IndicatorTrendDailyResponse = rawapi.IndicatorTrendDailyResponse

// IndicatorTrendDailyOutputItem aliases rawapi.IndicatorTrendDailyOutputItem.
type IndicatorTrendDailyOutputItem = rawapi.IndicatorTrendDailyOutputItem

// VolatilityTrendTickRequest aliases rawapi.VolatilityTrendTickRequest.
type VolatilityTrendTickRequest = rawapi.VolatilityTrendTickRequest

// VolatilityTrendTickResponse aliases rawapi.VolatilityTrendTickResponse.
type VolatilityTrendTickResponse = rawapi.VolatilityTrendTickResponse

// VolatilityTrendTickOutputItem aliases rawapi.VolatilityTrendTickOutputItem.
type VolatilityTrendTickOutputItem = rawapi.VolatilityTrendTickOutputItem

// VolatilityTrendCcnlRequest aliases rawapi.VolatilityTrendCcnlRequest.
type VolatilityTrendCcnlRequest = rawapi.VolatilityTrendCcnlRequest

// VolatilityTrendCcnlResponse aliases rawapi.VolatilityTrendCcnlResponse.
type VolatilityTrendCcnlResponse = rawapi.VolatilityTrendCcnlResponse

// VolatilityTrendCcnlOutputItem aliases rawapi.VolatilityTrendCcnlOutputItem.
type VolatilityTrendCcnlOutputItem = rawapi.VolatilityTrendCcnlOutputItem

// VolatilityTrendDailyRequest aliases rawapi.VolatilityTrendDailyRequest.
type VolatilityTrendDailyRequest = rawapi.VolatilityTrendDailyRequest

// VolatilityTrendDailyResponse aliases rawapi.VolatilityTrendDailyResponse.
type VolatilityTrendDailyResponse = rawapi.VolatilityTrendDailyResponse

// VolatilityTrendDailyOutputItem aliases rawapi.VolatilityTrendDailyOutputItem.
type VolatilityTrendDailyOutputItem = rawapi.VolatilityTrendDailyOutputItem

// SensitivityTrendCcnlRequest aliases rawapi.SensitivityTrendCcnlRequest.
type SensitivityTrendCcnlRequest = rawapi.SensitivityTrendCcnlRequest

// SensitivityTrendCcnlResponse aliases rawapi.SensitivityTrendCcnlResponse.
type SensitivityTrendCcnlResponse = rawapi.SensitivityTrendCcnlResponse

// SensitivityTrendCcnlOutputItem aliases rawapi.SensitivityTrendCcnlOutputItem.
type SensitivityTrendCcnlOutputItem = rawapi.SensitivityTrendCcnlOutputItem

// VolatilityTrendMinuteRequest aliases rawapi.VolatilityTrendMinuteRequest.
type VolatilityTrendMinuteRequest = rawapi.VolatilityTrendMinuteRequest

// VolatilityTrendMinuteResponse aliases rawapi.VolatilityTrendMinuteResponse.
type VolatilityTrendMinuteResponse = rawapi.VolatilityTrendMinuteResponse

// VolatilityTrendMinuteOutputItem aliases rawapi.VolatilityTrendMinuteOutputItem.
type VolatilityTrendMinuteOutputItem = rawapi.VolatilityTrendMinuteOutputItem

// SensitivityTrendDailyRequest aliases rawapi.SensitivityTrendDailyRequest.
type SensitivityTrendDailyRequest = rawapi.SensitivityTrendDailyRequest

// SensitivityTrendDailyResponse aliases rawapi.SensitivityTrendDailyResponse.
type SensitivityTrendDailyResponse = rawapi.SensitivityTrendDailyResponse

// SensitivityTrendDailyOutputItem aliases rawapi.SensitivityTrendDailyOutputItem.
type SensitivityTrendDailyOutputItem = rawapi.SensitivityTrendDailyOutputItem

// ExpirationStocksRequest aliases rawapi.ExpirationStocksRequest.
type ExpirationStocksRequest = rawapi.ExpirationStocksRequest

// ExpirationStocksResponse aliases rawapi.ExpirationStocksResponse.
type ExpirationStocksResponse = rawapi.ExpirationStocksResponse

// ExpirationStocksOutput1Item aliases rawapi.ExpirationStocksOutput1Item.
type ExpirationStocksOutput1Item = rawapi.ExpirationStocksOutput1Item

// IndicatorRequest aliases rawapi.IndicatorRequest.
type IndicatorRequest = rawapi.IndicatorRequest

// IndicatorResponse aliases rawapi.IndicatorResponse.
type IndicatorResponse = rawapi.IndicatorResponse

// IndicatorOutput1Item aliases rawapi.IndicatorOutput1Item.
type IndicatorOutput1Item = rawapi.IndicatorOutput1Item

// UpdownRateRequest aliases rawapi.UpdownRateRequest.
type UpdownRateRequest = rawapi.UpdownRateRequest

// UpdownRateResponse aliases rawapi.UpdownRateResponse.
type UpdownRateResponse = rawapi.UpdownRateResponse

// UpdownRateOutputItem aliases rawapi.UpdownRateOutputItem.
type UpdownRateOutputItem = rawapi.UpdownRateOutputItem

// ELWRankingVolumeRankRequest aliases rawapi.ELWRankingVolumeRankRequest.
type ELWRankingVolumeRankRequest = rawapi.ELWRankingVolumeRankRequest

// ELWRankingVolumeRankResponse aliases rawapi.ELWRankingVolumeRankResponse.
type ELWRankingVolumeRankResponse = rawapi.ELWRankingVolumeRankResponse

// ELWRankingVolumeRankOutputItem aliases rawapi.ELWRankingVolumeRankOutputItem.
type ELWRankingVolumeRankOutputItem = rawapi.ELWRankingVolumeRankOutputItem
