// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// InquireIndexPriceRequest aliases rawapi.InquireIndexPriceRequest.
type InquireIndexPriceRequest = rawapi.InquireIndexPriceRequest

// InquireIndexPriceResponse aliases rawapi.InquireIndexPriceResponse.
type InquireIndexPriceResponse = rawapi.InquireIndexPriceResponse

// InquireIndexPriceOutput aliases rawapi.InquireIndexPriceOutput.
type InquireIndexPriceOutput = rawapi.InquireIndexPriceOutput

// InquireIndexDailyPriceRequest aliases rawapi.InquireIndexDailyPriceRequest.
type InquireIndexDailyPriceRequest = rawapi.InquireIndexDailyPriceRequest

// InquireIndexDailyPriceResponse aliases rawapi.InquireIndexDailyPriceResponse.
type InquireIndexDailyPriceResponse = rawapi.InquireIndexDailyPriceResponse

// InquireIndexDailyPriceOutput1 aliases rawapi.InquireIndexDailyPriceOutput1.
type InquireIndexDailyPriceOutput1 = rawapi.InquireIndexDailyPriceOutput1

// InquireIndexDailyPriceOutput2Item aliases rawapi.InquireIndexDailyPriceOutput2Item.
type InquireIndexDailyPriceOutput2Item = rawapi.InquireIndexDailyPriceOutput2Item

// InquireIndexTickpriceRequest aliases rawapi.InquireIndexTickpriceRequest.
type InquireIndexTickpriceRequest = rawapi.InquireIndexTickpriceRequest

// InquireIndexTickpriceResponse aliases rawapi.InquireIndexTickpriceResponse.
type InquireIndexTickpriceResponse = rawapi.InquireIndexTickpriceResponse

// InquireIndexTickpriceOutputItem aliases rawapi.InquireIndexTickpriceOutputItem.
type InquireIndexTickpriceOutputItem = rawapi.InquireIndexTickpriceOutputItem

// InquireIndexTimepriceRequest aliases rawapi.InquireIndexTimepriceRequest.
type InquireIndexTimepriceRequest = rawapi.InquireIndexTimepriceRequest

// InquireIndexTimepriceResponse aliases rawapi.InquireIndexTimepriceResponse.
type InquireIndexTimepriceResponse = rawapi.InquireIndexTimepriceResponse

// InquireIndexTimepriceOutputItem aliases rawapi.InquireIndexTimepriceOutputItem.
type InquireIndexTimepriceOutputItem = rawapi.InquireIndexTimepriceOutputItem

// InquireTimeIndexchartpriceRequest aliases rawapi.InquireTimeIndexchartpriceRequest.
type InquireTimeIndexchartpriceRequest = rawapi.InquireTimeIndexchartpriceRequest

// InquireTimeIndexchartpriceResponse aliases rawapi.InquireTimeIndexchartpriceResponse.
type InquireTimeIndexchartpriceResponse = rawapi.InquireTimeIndexchartpriceResponse

// InquireTimeIndexchartpriceOutput1Item aliases rawapi.InquireTimeIndexchartpriceOutput1Item.
type InquireTimeIndexchartpriceOutput1Item = rawapi.InquireTimeIndexchartpriceOutput1Item

// InquireTimeIndexchartpriceOutput2 aliases rawapi.InquireTimeIndexchartpriceOutput2.
type InquireTimeIndexchartpriceOutput2 = rawapi.InquireTimeIndexchartpriceOutput2

// InquireDailyIndexchartpriceRequest aliases rawapi.InquireDailyIndexchartpriceRequest.
type InquireDailyIndexchartpriceRequest = rawapi.InquireDailyIndexchartpriceRequest

// InquireDailyIndexchartpriceResponse aliases rawapi.InquireDailyIndexchartpriceResponse.
type InquireDailyIndexchartpriceResponse = rawapi.InquireDailyIndexchartpriceResponse

// InquireDailyIndexchartpriceOutput1 aliases rawapi.InquireDailyIndexchartpriceOutput1.
type InquireDailyIndexchartpriceOutput1 = rawapi.InquireDailyIndexchartpriceOutput1

// InquireDailyIndexchartpriceOutput2Item aliases rawapi.InquireDailyIndexchartpriceOutput2Item.
type InquireDailyIndexchartpriceOutput2Item = rawapi.InquireDailyIndexchartpriceOutput2Item

// InquireIndexCategoryPriceRequest aliases rawapi.InquireIndexCategoryPriceRequest.
type InquireIndexCategoryPriceRequest = rawapi.InquireIndexCategoryPriceRequest

// InquireIndexCategoryPriceResponse aliases rawapi.InquireIndexCategoryPriceResponse.
type InquireIndexCategoryPriceResponse = rawapi.InquireIndexCategoryPriceResponse

// InquireIndexCategoryPriceOutput1 aliases rawapi.InquireIndexCategoryPriceOutput1.
type InquireIndexCategoryPriceOutput1 = rawapi.InquireIndexCategoryPriceOutput1

// InquireIndexCategoryPriceOutput2Item aliases rawapi.InquireIndexCategoryPriceOutput2Item.
type InquireIndexCategoryPriceOutput2Item = rawapi.InquireIndexCategoryPriceOutput2Item

// ExpIndexTrendRequest aliases rawapi.ExpIndexTrendRequest.
type ExpIndexTrendRequest = rawapi.ExpIndexTrendRequest

// ExpIndexTrendResponse aliases rawapi.ExpIndexTrendResponse.
type ExpIndexTrendResponse = rawapi.ExpIndexTrendResponse

// ExpIndexTrendOutputItem aliases rawapi.ExpIndexTrendOutputItem.
type ExpIndexTrendOutputItem = rawapi.ExpIndexTrendOutputItem

// ExpTotalIndexRequest aliases rawapi.ExpTotalIndexRequest.
type ExpTotalIndexRequest = rawapi.ExpTotalIndexRequest

// ExpTotalIndexResponse aliases rawapi.ExpTotalIndexResponse.
type ExpTotalIndexResponse = rawapi.ExpTotalIndexResponse

// ExpTotalIndexOutput1 aliases rawapi.ExpTotalIndexOutput1.
type ExpTotalIndexOutput1 = rawapi.ExpTotalIndexOutput1

// ExpTotalIndexOutput2Item aliases rawapi.ExpTotalIndexOutput2Item.
type ExpTotalIndexOutput2Item = rawapi.ExpTotalIndexOutput2Item

// InquireViStatusRequest aliases rawapi.InquireViStatusRequest.
type InquireViStatusRequest = rawapi.InquireViStatusRequest

// InquireViStatusResponse aliases rawapi.InquireViStatusResponse.
type InquireViStatusResponse = rawapi.InquireViStatusResponse

// InquireViStatusOutput aliases rawapi.InquireViStatusOutput.
type InquireViStatusOutput = rawapi.InquireViStatusOutput

// CompInterestRequest aliases rawapi.CompInterestRequest.
type CompInterestRequest = rawapi.CompInterestRequest

// CompInterestResponse aliases rawapi.CompInterestResponse.
type CompInterestResponse = rawapi.CompInterestResponse

// CompInterestOutput1 aliases rawapi.CompInterestOutput1.
type CompInterestOutput1 = rawapi.CompInterestOutput1

// CompInterestOutput2Item aliases rawapi.CompInterestOutput2Item.
type CompInterestOutput2Item = rawapi.CompInterestOutput2Item

// NewsTitleRequest aliases rawapi.NewsTitleRequest.
type NewsTitleRequest = rawapi.NewsTitleRequest

// NewsTitleResponse aliases rawapi.NewsTitleResponse.
type NewsTitleResponse = rawapi.NewsTitleResponse

// NewsTitleOutput aliases rawapi.NewsTitleOutput.
type NewsTitleOutput = rawapi.NewsTitleOutput

// ChkHolidayRequest aliases rawapi.ChkHolidayRequest.
type ChkHolidayRequest = rawapi.ChkHolidayRequest

// ChkHolidayResponse aliases rawapi.ChkHolidayResponse.
type ChkHolidayResponse = rawapi.ChkHolidayResponse

// ChkHolidayOutput aliases rawapi.ChkHolidayOutput.
type ChkHolidayOutput = rawapi.ChkHolidayOutput

// MarketTimeRequest aliases rawapi.MarketTimeRequest.
type MarketTimeRequest = rawapi.MarketTimeRequest

// MarketTimeResponse aliases rawapi.MarketTimeResponse.
type MarketTimeResponse = rawapi.MarketTimeResponse

// MarketTimeOutput1Item aliases rawapi.MarketTimeOutput1Item.
type MarketTimeOutput1Item = rawapi.MarketTimeOutput1Item
