// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// PsearchTitleRequest aliases rawapi.PsearchTitleRequest.
type PsearchTitleRequest = rawapi.PsearchTitleRequest

// PsearchTitleResponse aliases rawapi.PsearchTitleResponse.
type PsearchTitleResponse = rawapi.PsearchTitleResponse

// PsearchTitleOutput2Item aliases rawapi.PsearchTitleOutput2Item.
type PsearchTitleOutput2Item = rawapi.PsearchTitleOutput2Item

// PsearchResultRequest aliases rawapi.PsearchResultRequest.
type PsearchResultRequest = rawapi.PsearchResultRequest

// PsearchResultResponse aliases rawapi.PsearchResultResponse.
type PsearchResultResponse = rawapi.PsearchResultResponse

// PsearchResultOutput2Item aliases rawapi.PsearchResultOutput2Item.
type PsearchResultOutput2Item = rawapi.PsearchResultOutput2Item

// IntstockGrouplistRequest aliases rawapi.IntstockGrouplistRequest.
type IntstockGrouplistRequest = rawapi.IntstockGrouplistRequest

// IntstockGrouplistResponse aliases rawapi.IntstockGrouplistResponse.
type IntstockGrouplistResponse = rawapi.IntstockGrouplistResponse

// IntstockGrouplistOutput2 aliases rawapi.IntstockGrouplistOutput2.
type IntstockGrouplistOutput2 = rawapi.IntstockGrouplistOutput2

// IntstockMultpriceRequest aliases rawapi.IntstockMultpriceRequest.
type IntstockMultpriceRequest = rawapi.IntstockMultpriceRequest

// IntstockMultpriceResponse aliases rawapi.IntstockMultpriceResponse.
type IntstockMultpriceResponse = rawapi.IntstockMultpriceResponse

// IntstockMultpriceOutput aliases rawapi.IntstockMultpriceOutput.
type IntstockMultpriceOutput = rawapi.IntstockMultpriceOutput

// IntstockStocklistByGroupRequest aliases rawapi.IntstockStocklistByGroupRequest.
type IntstockStocklistByGroupRequest = rawapi.IntstockStocklistByGroupRequest

// IntstockStocklistByGroupResponse aliases rawapi.IntstockStocklistByGroupResponse.
type IntstockStocklistByGroupResponse = rawapi.IntstockStocklistByGroupResponse

// IntstockStocklistByGroupOutput1 aliases rawapi.IntstockStocklistByGroupOutput1.
type IntstockStocklistByGroupOutput1 = rawapi.IntstockStocklistByGroupOutput1

// IntstockStocklistByGroupOutput2Item aliases rawapi.IntstockStocklistByGroupOutput2Item.
type IntstockStocklistByGroupOutput2Item = rawapi.IntstockStocklistByGroupOutput2Item

// ForeignInstitutionTotalRequest aliases rawapi.ForeignInstitutionTotalRequest.
type ForeignInstitutionTotalRequest = rawapi.ForeignInstitutionTotalRequest

// ForeignInstitutionTotalResponse aliases rawapi.ForeignInstitutionTotalResponse.
type ForeignInstitutionTotalResponse = rawapi.ForeignInstitutionTotalResponse

// ForeignInstitutionTotalOutput aliases rawapi.ForeignInstitutionTotalOutput.
type ForeignInstitutionTotalOutput = rawapi.ForeignInstitutionTotalOutput

// FrgnmemTradeEstimateRequest aliases rawapi.FrgnmemTradeEstimateRequest.
type FrgnmemTradeEstimateRequest = rawapi.FrgnmemTradeEstimateRequest

// FrgnmemTradeEstimateResponse aliases rawapi.FrgnmemTradeEstimateResponse.
type FrgnmemTradeEstimateResponse = rawapi.FrgnmemTradeEstimateResponse

// FrgnmemTradeEstimateOutputItem aliases rawapi.FrgnmemTradeEstimateOutputItem.
type FrgnmemTradeEstimateOutputItem = rawapi.FrgnmemTradeEstimateOutputItem

// InvestorTradeByStockDailyRequest aliases rawapi.InvestorTradeByStockDailyRequest.
type InvestorTradeByStockDailyRequest = rawapi.InvestorTradeByStockDailyRequest

// InvestorTradeByStockDailyResponse aliases rawapi.InvestorTradeByStockDailyResponse.
type InvestorTradeByStockDailyResponse = rawapi.InvestorTradeByStockDailyResponse

// InvestorTradeByStockDailyOutput1 aliases rawapi.InvestorTradeByStockDailyOutput1.
type InvestorTradeByStockDailyOutput1 = rawapi.InvestorTradeByStockDailyOutput1

// InvestorTradeByStockDailyOutput2Item aliases rawapi.InvestorTradeByStockDailyOutput2Item.
type InvestorTradeByStockDailyOutput2Item = rawapi.InvestorTradeByStockDailyOutput2Item

// InquireInvestorTimeByMarketRequest aliases rawapi.InquireInvestorTimeByMarketRequest.
type InquireInvestorTimeByMarketRequest = rawapi.InquireInvestorTimeByMarketRequest

// InquireInvestorTimeByMarketResponse aliases rawapi.InquireInvestorTimeByMarketResponse.
type InquireInvestorTimeByMarketResponse = rawapi.InquireInvestorTimeByMarketResponse

// InquireInvestorTimeByMarketOutput aliases rawapi.InquireInvestorTimeByMarketOutput.
type InquireInvestorTimeByMarketOutput = rawapi.InquireInvestorTimeByMarketOutput

// InquireInvestorDailyByMarketRequest aliases rawapi.InquireInvestorDailyByMarketRequest.
type InquireInvestorDailyByMarketRequest = rawapi.InquireInvestorDailyByMarketRequest

// InquireInvestorDailyByMarketResponse aliases rawapi.InquireInvestorDailyByMarketResponse.
type InquireInvestorDailyByMarketResponse = rawapi.InquireInvestorDailyByMarketResponse

// InquireInvestorDailyByMarketOutputItem aliases rawapi.InquireInvestorDailyByMarketOutputItem.
type InquireInvestorDailyByMarketOutputItem = rawapi.InquireInvestorDailyByMarketOutputItem

// FrgnmemPchsTrendRequest aliases rawapi.FrgnmemPchsTrendRequest.
type FrgnmemPchsTrendRequest = rawapi.FrgnmemPchsTrendRequest

// FrgnmemPchsTrendResponse aliases rawapi.FrgnmemPchsTrendResponse.
type FrgnmemPchsTrendResponse = rawapi.FrgnmemPchsTrendResponse

// FrgnmemPchsTrendOutputItem aliases rawapi.FrgnmemPchsTrendOutputItem.
type FrgnmemPchsTrendOutputItem = rawapi.FrgnmemPchsTrendOutputItem

// FrgnmemTradeTrendRequest aliases rawapi.FrgnmemTradeTrendRequest.
type FrgnmemTradeTrendRequest = rawapi.FrgnmemTradeTrendRequest

// FrgnmemTradeTrendResponse aliases rawapi.FrgnmemTradeTrendResponse.
type FrgnmemTradeTrendResponse = rawapi.FrgnmemTradeTrendResponse

// FrgnmemTradeTrendOutput1 aliases rawapi.FrgnmemTradeTrendOutput1.
type FrgnmemTradeTrendOutput1 = rawapi.FrgnmemTradeTrendOutput1

// FrgnmemTradeTrendOutput2Item aliases rawapi.FrgnmemTradeTrendOutput2Item.
type FrgnmemTradeTrendOutput2Item = rawapi.FrgnmemTradeTrendOutput2Item

// InquireMemberDailyRequest aliases rawapi.InquireMemberDailyRequest.
type InquireMemberDailyRequest = rawapi.InquireMemberDailyRequest

// InquireMemberDailyResponse aliases rawapi.InquireMemberDailyResponse.
type InquireMemberDailyResponse = rawapi.InquireMemberDailyResponse

// InquireMemberDailyOutputItem aliases rawapi.InquireMemberDailyOutputItem.
type InquireMemberDailyOutputItem = rawapi.InquireMemberDailyOutputItem

// ProgramTradeByStockRequest aliases rawapi.ProgramTradeByStockRequest.
type ProgramTradeByStockRequest = rawapi.ProgramTradeByStockRequest

// ProgramTradeByStockResponse aliases rawapi.ProgramTradeByStockResponse.
type ProgramTradeByStockResponse = rawapi.ProgramTradeByStockResponse

// ProgramTradeByStockOutputItem aliases rawapi.ProgramTradeByStockOutputItem.
type ProgramTradeByStockOutputItem = rawapi.ProgramTradeByStockOutputItem

// ProgramTradeByStockDailyRequest aliases rawapi.ProgramTradeByStockDailyRequest.
type ProgramTradeByStockDailyRequest = rawapi.ProgramTradeByStockDailyRequest

// ProgramTradeByStockDailyResponse aliases rawapi.ProgramTradeByStockDailyResponse.
type ProgramTradeByStockDailyResponse = rawapi.ProgramTradeByStockDailyResponse

// ProgramTradeByStockDailyOutputItem aliases rawapi.ProgramTradeByStockDailyOutputItem.
type ProgramTradeByStockDailyOutputItem = rawapi.ProgramTradeByStockDailyOutputItem

// InvestorTrendEstimateRequest aliases rawapi.InvestorTrendEstimateRequest.
type InvestorTrendEstimateRequest = rawapi.InvestorTrendEstimateRequest

// InvestorTrendEstimateResponse aliases rawapi.InvestorTrendEstimateResponse.
type InvestorTrendEstimateResponse = rawapi.InvestorTrendEstimateResponse

// InvestorTrendEstimateOutput2Item aliases rawapi.InvestorTrendEstimateOutput2Item.
type InvestorTrendEstimateOutput2Item = rawapi.InvestorTrendEstimateOutput2Item

// InquireDailyTradeVolumeRequest aliases rawapi.InquireDailyTradeVolumeRequest.
type InquireDailyTradeVolumeRequest = rawapi.InquireDailyTradeVolumeRequest

// InquireDailyTradeVolumeResponse aliases rawapi.InquireDailyTradeVolumeResponse.
type InquireDailyTradeVolumeResponse = rawapi.InquireDailyTradeVolumeResponse

// InquireDailyTradeVolumeOutput1 aliases rawapi.InquireDailyTradeVolumeOutput1.
type InquireDailyTradeVolumeOutput1 = rawapi.InquireDailyTradeVolumeOutput1

// InquireDailyTradeVolumeOutput2Item aliases rawapi.InquireDailyTradeVolumeOutput2Item.
type InquireDailyTradeVolumeOutput2Item = rawapi.InquireDailyTradeVolumeOutput2Item

// CompProgramTradeTodayRequest aliases rawapi.CompProgramTradeTodayRequest.
type CompProgramTradeTodayRequest = rawapi.CompProgramTradeTodayRequest

// CompProgramTradeTodayResponse aliases rawapi.CompProgramTradeTodayResponse.
type CompProgramTradeTodayResponse = rawapi.CompProgramTradeTodayResponse

// CompProgramTradeTodayOutput1Item aliases rawapi.CompProgramTradeTodayOutput1Item.
type CompProgramTradeTodayOutput1Item = rawapi.CompProgramTradeTodayOutput1Item

// CompProgramTradeDailyRequest aliases rawapi.CompProgramTradeDailyRequest.
type CompProgramTradeDailyRequest = rawapi.CompProgramTradeDailyRequest

// CompProgramTradeDailyResponse aliases rawapi.CompProgramTradeDailyResponse.
type CompProgramTradeDailyResponse = rawapi.CompProgramTradeDailyResponse

// CompProgramTradeDailyOutputItem aliases rawapi.CompProgramTradeDailyOutputItem.
type CompProgramTradeDailyOutputItem = rawapi.CompProgramTradeDailyOutputItem

// InvestorProgramTradeTodayRequest aliases rawapi.InvestorProgramTradeTodayRequest.
type InvestorProgramTradeTodayRequest = rawapi.InvestorProgramTradeTodayRequest

// InvestorProgramTradeTodayResponse aliases rawapi.InvestorProgramTradeTodayResponse.
type InvestorProgramTradeTodayResponse = rawapi.InvestorProgramTradeTodayResponse

// InvestorProgramTradeTodayOutput1Item aliases rawapi.InvestorProgramTradeTodayOutput1Item.
type InvestorProgramTradeTodayOutput1Item = rawapi.InvestorProgramTradeTodayOutput1Item

// DailyCreditBalanceRequest aliases rawapi.DailyCreditBalanceRequest.
type DailyCreditBalanceRequest = rawapi.DailyCreditBalanceRequest

// DailyCreditBalanceResponse aliases rawapi.DailyCreditBalanceResponse.
type DailyCreditBalanceResponse = rawapi.DailyCreditBalanceResponse

// DailyCreditBalanceOutputItem aliases rawapi.DailyCreditBalanceOutputItem.
type DailyCreditBalanceOutputItem = rawapi.DailyCreditBalanceOutputItem

// ExpPriceTrendRequest aliases rawapi.ExpPriceTrendRequest.
type ExpPriceTrendRequest = rawapi.ExpPriceTrendRequest

// ExpPriceTrendResponse aliases rawapi.ExpPriceTrendResponse.
type ExpPriceTrendResponse = rawapi.ExpPriceTrendResponse

// ExpPriceTrendOutput1 aliases rawapi.ExpPriceTrendOutput1.
type ExpPriceTrendOutput1 = rawapi.ExpPriceTrendOutput1

// ExpPriceTrendOutput2Item aliases rawapi.ExpPriceTrendOutput2Item.
type ExpPriceTrendOutput2Item = rawapi.ExpPriceTrendOutput2Item

// DailyShortSaleRequest aliases rawapi.DailyShortSaleRequest.
type DailyShortSaleRequest = rawapi.DailyShortSaleRequest

// DailyShortSaleResponse aliases rawapi.DailyShortSaleResponse.
type DailyShortSaleResponse = rawapi.DailyShortSaleResponse

// DailyShortSaleOutput1 aliases rawapi.DailyShortSaleOutput1.
type DailyShortSaleOutput1 = rawapi.DailyShortSaleOutput1

// DailyShortSaleOutput2Item aliases rawapi.DailyShortSaleOutput2Item.
type DailyShortSaleOutput2Item = rawapi.DailyShortSaleOutput2Item

// OvertimeExpTransFluctRequest aliases rawapi.OvertimeExpTransFluctRequest.
type OvertimeExpTransFluctRequest = rawapi.OvertimeExpTransFluctRequest

// OvertimeExpTransFluctResponse aliases rawapi.OvertimeExpTransFluctResponse.
type OvertimeExpTransFluctResponse = rawapi.OvertimeExpTransFluctResponse

// OvertimeExpTransFluctOutput aliases rawapi.OvertimeExpTransFluctOutput.
type OvertimeExpTransFluctOutput = rawapi.OvertimeExpTransFluctOutput

// TradprtByamtRequest aliases rawapi.TradprtByamtRequest.
type TradprtByamtRequest = rawapi.TradprtByamtRequest

// TradprtByamtResponse aliases rawapi.TradprtByamtResponse.
type TradprtByamtResponse = rawapi.TradprtByamtResponse

// TradprtByamtOutputItem aliases rawapi.TradprtByamtOutputItem.
type TradprtByamtOutputItem = rawapi.TradprtByamtOutputItem

// MktfundsRequest aliases rawapi.MktfundsRequest.
type MktfundsRequest = rawapi.MktfundsRequest

// MktfundsResponse aliases rawapi.MktfundsResponse.
type MktfundsResponse = rawapi.MktfundsResponse

// MktfundsOutputItem aliases rawapi.MktfundsOutputItem.
type MktfundsOutputItem = rawapi.MktfundsOutputItem

// DailyLoanTransRequest aliases rawapi.DailyLoanTransRequest.
type DailyLoanTransRequest = rawapi.DailyLoanTransRequest

// DailyLoanTransResponse aliases rawapi.DailyLoanTransResponse.
type DailyLoanTransResponse = rawapi.DailyLoanTransResponse

// DailyLoanTransOutput1Item aliases rawapi.DailyLoanTransOutput1Item.
type DailyLoanTransOutput1Item = rawapi.DailyLoanTransOutput1Item

// CaptureUplowpriceRequest aliases rawapi.CaptureUplowpriceRequest.
type CaptureUplowpriceRequest = rawapi.CaptureUplowpriceRequest

// CaptureUplowpriceResponse aliases rawapi.CaptureUplowpriceResponse.
type CaptureUplowpriceResponse = rawapi.CaptureUplowpriceResponse

// CaptureUplowpriceOutputItem aliases rawapi.CaptureUplowpriceOutputItem.
type CaptureUplowpriceOutputItem = rawapi.CaptureUplowpriceOutputItem

// PbarTratioRequest aliases rawapi.PbarTratioRequest.
type PbarTratioRequest = rawapi.PbarTratioRequest

// PbarTratioResponse aliases rawapi.PbarTratioResponse.
type PbarTratioResponse = rawapi.PbarTratioResponse

// PbarTratioOutput1 aliases rawapi.PbarTratioOutput1.
type PbarTratioOutput1 = rawapi.PbarTratioOutput1

// PbarTratioOutput2Item aliases rawapi.PbarTratioOutput2Item.
type PbarTratioOutput2Item = rawapi.PbarTratioOutput2Item
