// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// VolumeRankRequest aliases rawapi.VolumeRankRequest.
type VolumeRankRequest = rawapi.VolumeRankRequest

// VolumeRankResponse aliases rawapi.VolumeRankResponse.
type VolumeRankResponse = rawapi.VolumeRankResponse

// VolumeRankOutputItem aliases rawapi.VolumeRankOutputItem.
type VolumeRankOutputItem = rawapi.VolumeRankOutputItem

// FluctuationRequest aliases rawapi.FluctuationRequest.
type FluctuationRequest = rawapi.FluctuationRequest

// FluctuationResponse aliases rawapi.FluctuationResponse.
type FluctuationResponse = rawapi.FluctuationResponse

// FluctuationOutputItem aliases rawapi.FluctuationOutputItem.
type FluctuationOutputItem = rawapi.FluctuationOutputItem

// QuoteBalanceRequest aliases rawapi.QuoteBalanceRequest.
type QuoteBalanceRequest = rawapi.QuoteBalanceRequest

// QuoteBalanceResponse aliases rawapi.QuoteBalanceResponse.
type QuoteBalanceResponse = rawapi.QuoteBalanceResponse

// QuoteBalanceOutputItem aliases rawapi.QuoteBalanceOutputItem.
type QuoteBalanceOutputItem = rawapi.QuoteBalanceOutputItem

// ProfitAssetIndexRequest aliases rawapi.ProfitAssetIndexRequest.
type ProfitAssetIndexRequest = rawapi.ProfitAssetIndexRequest

// ProfitAssetIndexResponse aliases rawapi.ProfitAssetIndexResponse.
type ProfitAssetIndexResponse = rawapi.ProfitAssetIndexResponse

// ProfitAssetIndexOutputItem aliases rawapi.ProfitAssetIndexOutputItem.
type ProfitAssetIndexOutputItem = rawapi.ProfitAssetIndexOutputItem

// MarketCapRequest aliases rawapi.MarketCapRequest.
type MarketCapRequest = rawapi.MarketCapRequest

// MarketCapResponse aliases rawapi.MarketCapResponse.
type MarketCapResponse = rawapi.MarketCapResponse

// MarketCapOutputItem aliases rawapi.MarketCapOutputItem.
type MarketCapOutputItem = rawapi.MarketCapOutputItem

// FinanceRatioRequest aliases rawapi.FinanceRatioRequest.
type FinanceRatioRequest = rawapi.FinanceRatioRequest

// FinanceRatioResponse aliases rawapi.FinanceRatioResponse.
type FinanceRatioResponse = rawapi.FinanceRatioResponse

// FinanceRatioOutputItem aliases rawapi.FinanceRatioOutputItem.
type FinanceRatioOutputItem = rawapi.FinanceRatioOutputItem

// AfterHourBalanceRequest aliases rawapi.AfterHourBalanceRequest.
type AfterHourBalanceRequest = rawapi.AfterHourBalanceRequest

// AfterHourBalanceResponse aliases rawapi.AfterHourBalanceResponse.
type AfterHourBalanceResponse = rawapi.AfterHourBalanceResponse

// AfterHourBalanceOutputItem aliases rawapi.AfterHourBalanceOutputItem.
type AfterHourBalanceOutputItem = rawapi.AfterHourBalanceOutputItem

// PreferDisparateRatioRequest aliases rawapi.PreferDisparateRatioRequest.
type PreferDisparateRatioRequest = rawapi.PreferDisparateRatioRequest

// PreferDisparateRatioResponse aliases rawapi.PreferDisparateRatioResponse.
type PreferDisparateRatioResponse = rawapi.PreferDisparateRatioResponse

// PreferDisparateRatioOutputItem aliases rawapi.PreferDisparateRatioOutputItem.
type PreferDisparateRatioOutputItem = rawapi.PreferDisparateRatioOutputItem

// DisparityRequest aliases rawapi.DisparityRequest.
type DisparityRequest = rawapi.DisparityRequest

// DisparityResponse aliases rawapi.DisparityResponse.
type DisparityResponse = rawapi.DisparityResponse

// DisparityOutputItem aliases rawapi.DisparityOutputItem.
type DisparityOutputItem = rawapi.DisparityOutputItem

// MarketValueRequest aliases rawapi.MarketValueRequest.
type MarketValueRequest = rawapi.MarketValueRequest

// MarketValueResponse aliases rawapi.MarketValueResponse.
type MarketValueResponse = rawapi.MarketValueResponse

// MarketValueOutputItem aliases rawapi.MarketValueOutputItem.
type MarketValueOutputItem = rawapi.MarketValueOutputItem

// VolumePowerRequest aliases rawapi.VolumePowerRequest.
type VolumePowerRequest = rawapi.VolumePowerRequest

// VolumePowerResponse aliases rawapi.VolumePowerResponse.
type VolumePowerResponse = rawapi.VolumePowerResponse

// VolumePowerOutputItem aliases rawapi.VolumePowerOutputItem.
type VolumePowerOutputItem = rawapi.VolumePowerOutputItem

// TopInterestStockRequest aliases rawapi.TopInterestStockRequest.
type TopInterestStockRequest = rawapi.TopInterestStockRequest

// TopInterestStockResponse aliases rawapi.TopInterestStockResponse.
type TopInterestStockResponse = rawapi.TopInterestStockResponse

// TopInterestStockOutputItem aliases rawapi.TopInterestStockOutputItem.
type TopInterestStockOutputItem = rawapi.TopInterestStockOutputItem

// ExpTransUpdownRequest aliases rawapi.ExpTransUpdownRequest.
type ExpTransUpdownRequest = rawapi.ExpTransUpdownRequest

// ExpTransUpdownResponse aliases rawapi.ExpTransUpdownResponse.
type ExpTransUpdownResponse = rawapi.ExpTransUpdownResponse

// ExpTransUpdownOutputItem aliases rawapi.ExpTransUpdownOutputItem.
type ExpTransUpdownOutputItem = rawapi.ExpTransUpdownOutputItem

// TradedByCompanyRequest aliases rawapi.TradedByCompanyRequest.
type TradedByCompanyRequest = rawapi.TradedByCompanyRequest

// TradedByCompanyResponse aliases rawapi.TradedByCompanyResponse.
type TradedByCompanyResponse = rawapi.TradedByCompanyResponse

// TradedByCompanyOutputItem aliases rawapi.TradedByCompanyOutputItem.
type TradedByCompanyOutputItem = rawapi.TradedByCompanyOutputItem

// NearNewHighlowRequest aliases rawapi.NearNewHighlowRequest.
type NearNewHighlowRequest = rawapi.NearNewHighlowRequest

// NearNewHighlowResponse aliases rawapi.NearNewHighlowResponse.
type NearNewHighlowResponse = rawapi.NearNewHighlowResponse

// NearNewHighlowOutputItem aliases rawapi.NearNewHighlowOutputItem.
type NearNewHighlowOutputItem = rawapi.NearNewHighlowOutputItem

// DividendRateRequest aliases rawapi.DividendRateRequest.
type DividendRateRequest = rawapi.DividendRateRequest

// DividendRateResponse aliases rawapi.DividendRateResponse.
type DividendRateResponse = rawapi.DividendRateResponse

// DividendRateOutput1Item aliases rawapi.DividendRateOutput1Item.
type DividendRateOutput1Item = rawapi.DividendRateOutput1Item

// BulkTransNumRequest aliases rawapi.BulkTransNumRequest.
type BulkTransNumRequest = rawapi.BulkTransNumRequest

// BulkTransNumResponse aliases rawapi.BulkTransNumResponse.
type BulkTransNumResponse = rawapi.BulkTransNumResponse

// BulkTransNumOutputItem aliases rawapi.BulkTransNumOutputItem.
type BulkTransNumOutputItem = rawapi.BulkTransNumOutputItem

// CreditBalanceRequest aliases rawapi.CreditBalanceRequest.
type CreditBalanceRequest = rawapi.CreditBalanceRequest

// CreditBalanceResponse aliases rawapi.CreditBalanceResponse.
type CreditBalanceResponse = rawapi.CreditBalanceResponse

// CreditBalanceOutput1Item aliases rawapi.CreditBalanceOutput1Item.
type CreditBalanceOutput1Item = rawapi.CreditBalanceOutput1Item

// CreditBalanceOutput2Item aliases rawapi.CreditBalanceOutput2Item.
type CreditBalanceOutput2Item = rawapi.CreditBalanceOutput2Item

// ShortSaleRequest aliases rawapi.ShortSaleRequest.
type ShortSaleRequest = rawapi.ShortSaleRequest

// ShortSaleResponse aliases rawapi.ShortSaleResponse.
type ShortSaleResponse = rawapi.ShortSaleResponse

// ShortSaleOutputItem aliases rawapi.ShortSaleOutputItem.
type ShortSaleOutputItem = rawapi.ShortSaleOutputItem

// OvertimeFluctuationRequest aliases rawapi.OvertimeFluctuationRequest.
type OvertimeFluctuationRequest = rawapi.OvertimeFluctuationRequest

// OvertimeFluctuationResponse aliases rawapi.OvertimeFluctuationResponse.
type OvertimeFluctuationResponse = rawapi.OvertimeFluctuationResponse

// OvertimeFluctuationOutput1 aliases rawapi.OvertimeFluctuationOutput1.
type OvertimeFluctuationOutput1 = rawapi.OvertimeFluctuationOutput1

// OvertimeFluctuationOutput2Item aliases rawapi.OvertimeFluctuationOutput2Item.
type OvertimeFluctuationOutput2Item = rawapi.OvertimeFluctuationOutput2Item

// OvertimeVolumeRequest aliases rawapi.OvertimeVolumeRequest.
type OvertimeVolumeRequest = rawapi.OvertimeVolumeRequest

// OvertimeVolumeResponse aliases rawapi.OvertimeVolumeResponse.
type OvertimeVolumeResponse = rawapi.OvertimeVolumeResponse

// OvertimeVolumeOutput1 aliases rawapi.OvertimeVolumeOutput1.
type OvertimeVolumeOutput1 = rawapi.OvertimeVolumeOutput1

// OvertimeVolumeOutput2Item aliases rawapi.OvertimeVolumeOutput2Item.
type OvertimeVolumeOutput2Item = rawapi.OvertimeVolumeOutput2Item

// HtsTopViewRequest aliases rawapi.HtsTopViewRequest.
type HtsTopViewRequest = rawapi.HtsTopViewRequest

// HtsTopViewResponse aliases rawapi.HtsTopViewResponse.
type HtsTopViewResponse = rawapi.HtsTopViewResponse

// HtsTopViewOutput1 aliases rawapi.HtsTopViewOutput1.
type HtsTopViewOutput1 = rawapi.HtsTopViewOutput1
