// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// InquirePriceRequest aliases rawapi.InquirePriceRequest.
type InquirePriceRequest = rawapi.InquirePriceRequest

// InquirePriceResponse aliases rawapi.InquirePriceResponse.
type InquirePriceResponse = rawapi.InquirePriceResponse

// InquirePriceOutput aliases rawapi.InquirePriceOutput.
type InquirePriceOutput = rawapi.InquirePriceOutput

// InquireCcnlRequest aliases rawapi.InquireCcnlRequest.
type InquireCcnlRequest = rawapi.InquireCcnlRequest

// InquireCcnlResponse aliases rawapi.InquireCcnlResponse.
type InquireCcnlResponse = rawapi.InquireCcnlResponse

// InquireCcnlOutputItem aliases rawapi.InquireCcnlOutputItem.
type InquireCcnlOutputItem = rawapi.InquireCcnlOutputItem

// InquireDailyPriceRequest aliases rawapi.InquireDailyPriceRequest.
type InquireDailyPriceRequest = rawapi.InquireDailyPriceRequest

// InquireDailyPriceResponse aliases rawapi.InquireDailyPriceResponse.
type InquireDailyPriceResponse = rawapi.InquireDailyPriceResponse

// InquireDailyPriceOutputItem aliases rawapi.InquireDailyPriceOutputItem.
type InquireDailyPriceOutputItem = rawapi.InquireDailyPriceOutputItem

// InquireAskingPriceExpCcnRequest aliases rawapi.InquireAskingPriceExpCcnRequest.
type InquireAskingPriceExpCcnRequest = rawapi.InquireAskingPriceExpCcnRequest

// InquireAskingPriceExpCcnResponse aliases rawapi.InquireAskingPriceExpCcnResponse.
type InquireAskingPriceExpCcnResponse = rawapi.InquireAskingPriceExpCcnResponse

// InquireAskingPriceExpCcnOutput1 aliases rawapi.InquireAskingPriceExpCcnOutput1.
type InquireAskingPriceExpCcnOutput1 = rawapi.InquireAskingPriceExpCcnOutput1

// InquireAskingPriceExpCcnOutput2 aliases rawapi.InquireAskingPriceExpCcnOutput2.
type InquireAskingPriceExpCcnOutput2 = rawapi.InquireAskingPriceExpCcnOutput2

// InquireInvestorRequest aliases rawapi.InquireInvestorRequest.
type InquireInvestorRequest = rawapi.InquireInvestorRequest

// InquireInvestorResponse aliases rawapi.InquireInvestorResponse.
type InquireInvestorResponse = rawapi.InquireInvestorResponse

// InquireInvestorOutputItem aliases rawapi.InquireInvestorOutputItem.
type InquireInvestorOutputItem = rawapi.InquireInvestorOutputItem

// InquireMemberRequest aliases rawapi.InquireMemberRequest.
type InquireMemberRequest = rawapi.InquireMemberRequest

// InquireMemberResponse aliases rawapi.InquireMemberResponse.
type InquireMemberResponse = rawapi.InquireMemberResponse

// InquireDailyItemChartPriceRequest aliases rawapi.InquireDailyItemChartPriceRequest.
type InquireDailyItemChartPriceRequest = rawapi.InquireDailyItemChartPriceRequest

// InquireDailyItemChartPriceResponse aliases rawapi.InquireDailyItemChartPriceResponse.
type InquireDailyItemChartPriceResponse = rawapi.InquireDailyItemChartPriceResponse

// InquireDailyItemChartPriceOutput1 aliases rawapi.InquireDailyItemChartPriceOutput1.
type InquireDailyItemChartPriceOutput1 = rawapi.InquireDailyItemChartPriceOutput1

// InquireDailyItemChartPriceOutput2Item aliases rawapi.InquireDailyItemChartPriceOutput2Item.
type InquireDailyItemChartPriceOutput2Item = rawapi.InquireDailyItemChartPriceOutput2Item

// InquireTimeItemChartPriceRequest aliases rawapi.InquireTimeItemChartPriceRequest.
type InquireTimeItemChartPriceRequest = rawapi.InquireTimeItemChartPriceRequest

// InquireTimeItemChartPriceResponse aliases rawapi.InquireTimeItemChartPriceResponse.
type InquireTimeItemChartPriceResponse = rawapi.InquireTimeItemChartPriceResponse

// InquireTimeItemChartPriceOutput1 aliases rawapi.InquireTimeItemChartPriceOutput1.
type InquireTimeItemChartPriceOutput1 = rawapi.InquireTimeItemChartPriceOutput1

// InquireTimeItemChartPriceOutput2Item aliases rawapi.InquireTimeItemChartPriceOutput2Item.
type InquireTimeItemChartPriceOutput2Item = rawapi.InquireTimeItemChartPriceOutput2Item

// InquireTimeItemConclusionRequest aliases rawapi.InquireTimeItemConclusionRequest.
type InquireTimeItemConclusionRequest = rawapi.InquireTimeItemConclusionRequest

// InquireTimeItemConclusionResponse aliases rawapi.InquireTimeItemConclusionResponse.
type InquireTimeItemConclusionResponse = rawapi.InquireTimeItemConclusionResponse

// InquireTimeItemConclusionOutput1 aliases rawapi.InquireTimeItemConclusionOutput1.
type InquireTimeItemConclusionOutput1 = rawapi.InquireTimeItemConclusionOutput1

// InquireTimeItemConclusionOutput2 aliases rawapi.InquireTimeItemConclusionOutput2.
type InquireTimeItemConclusionOutput2 = rawapi.InquireTimeItemConclusionOutput2
