// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// VolumeRankRequest aliases rawapi.VolumeRankRequest.
type VolumeRankRequest = rawapi.VolumeRankRequest

// VolumeRankResponse aliases rawapi.VolumeRankResponse.
type VolumeRankResponse = rawapi.VolumeRankResponse

// VolumeRankOutputItem aliases rawapi.VolumeRankOutputItem.
type VolumeRankOutputItem = rawapi.VolumeRankOutputItem

// FluctuationRequest aliases rawapi.FluctuationRequest.
type FluctuationRequest = rawapi.FluctuationRequest

// FluctuationResponse aliases rawapi.FluctuationResponse.
type FluctuationResponse = rawapi.FluctuationResponse

// FluctuationOutputItem aliases rawapi.FluctuationOutputItem.
type FluctuationOutputItem = rawapi.FluctuationOutputItem

// MarketCapRequest aliases rawapi.MarketCapRequest.
type MarketCapRequest = rawapi.MarketCapRequest

// MarketCapResponse aliases rawapi.MarketCapResponse.
type MarketCapResponse = rawapi.MarketCapResponse

// MarketCapOutputItem aliases rawapi.MarketCapOutputItem.
type MarketCapOutputItem = rawapi.MarketCapOutputItem

// MarketValueRequest aliases rawapi.MarketValueRequest.
type MarketValueRequest = rawapi.MarketValueRequest

// MarketValueResponse aliases rawapi.MarketValueResponse.
type MarketValueResponse = rawapi.MarketValueResponse

// MarketValueOutputItem aliases rawapi.MarketValueOutputItem.
type MarketValueOutputItem = rawapi.MarketValueOutputItem

// VolumePowerRequest aliases rawapi.VolumePowerRequest.
type VolumePowerRequest = rawapi.VolumePowerRequest

// VolumePowerResponse aliases rawapi.VolumePowerResponse.
type VolumePowerResponse = rawapi.VolumePowerResponse

// VolumePowerOutputItem aliases rawapi.VolumePowerOutputItem.
type VolumePowerOutputItem = rawapi.VolumePowerOutputItem
