// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import "github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"

// SearchInfoRequest aliases rawapi.SearchInfoRequest.
type SearchInfoRequest = rawapi.SearchInfoRequest

// SearchInfoResponse aliases rawapi.SearchInfoResponse.
type SearchInfoResponse = rawapi.SearchInfoResponse

// SearchInfoOutput aliases rawapi.SearchInfoOutput.
type SearchInfoOutput = rawapi.SearchInfoOutput

// SearchStockInfoRequest aliases rawapi.SearchStockInfoRequest.
type SearchStockInfoRequest = rawapi.SearchStockInfoRequest

// SearchStockInfoResponse aliases rawapi.SearchStockInfoResponse.
type SearchStockInfoResponse = rawapi.SearchStockInfoResponse

// SearchStockInfoOutput aliases rawapi.SearchStockInfoOutput.
type SearchStockInfoOutput = rawapi.SearchStockInfoOutput

// BalanceSheetRequest aliases rawapi.BalanceSheetRequest.
type BalanceSheetRequest = rawapi.BalanceSheetRequest

// BalanceSheetResponse aliases rawapi.BalanceSheetResponse.
type BalanceSheetResponse = rawapi.BalanceSheetResponse

// BalanceSheetOutputItem aliases rawapi.BalanceSheetOutputItem.
type BalanceSheetOutputItem = rawapi.BalanceSheetOutputItem

// IncomeStatementRequest aliases rawapi.IncomeStatementRequest.
type IncomeStatementRequest = rawapi.IncomeStatementRequest

// IncomeStatementResponse aliases rawapi.IncomeStatementResponse.
type IncomeStatementResponse = rawapi.IncomeStatementResponse

// IncomeStatementOutputItem aliases rawapi.IncomeStatementOutputItem.
type IncomeStatementOutputItem = rawapi.IncomeStatementOutputItem

// FinancialRatioRequest aliases rawapi.FinancialRatioRequest.
type FinancialRatioRequest = rawapi.FinancialRatioRequest

// FinancialRatioResponse aliases rawapi.FinancialRatioResponse.
type FinancialRatioResponse = rawapi.FinancialRatioResponse

// FinancialRatioOutputItem aliases rawapi.FinancialRatioOutputItem.
type FinancialRatioOutputItem = rawapi.FinancialRatioOutputItem

// ProfitRatioRequest aliases rawapi.ProfitRatioRequest.
type ProfitRatioRequest = rawapi.ProfitRatioRequest

// ProfitRatioResponse aliases rawapi.ProfitRatioResponse.
type ProfitRatioResponse = rawapi.ProfitRatioResponse

// ProfitRatioOutputItem aliases rawapi.ProfitRatioOutputItem.
type ProfitRatioOutputItem = rawapi.ProfitRatioOutputItem

// OtherMajorRatiosRequest aliases rawapi.OtherMajorRatiosRequest.
type OtherMajorRatiosRequest = rawapi.OtherMajorRatiosRequest

// OtherMajorRatiosResponse aliases rawapi.OtherMajorRatiosResponse.
type OtherMajorRatiosResponse = rawapi.OtherMajorRatiosResponse

// OtherMajorRatiosOutputItem aliases rawapi.OtherMajorRatiosOutputItem.
type OtherMajorRatiosOutputItem = rawapi.OtherMajorRatiosOutputItem

// StabilityRatioRequest aliases rawapi.StabilityRatioRequest.
type StabilityRatioRequest = rawapi.StabilityRatioRequest

// StabilityRatioResponse aliases rawapi.StabilityRatioResponse.
type StabilityRatioResponse = rawapi.StabilityRatioResponse

// StabilityRatioOutputItem aliases rawapi.StabilityRatioOutputItem.
type StabilityRatioOutputItem = rawapi.StabilityRatioOutputItem

// GrowthRatioRequest aliases rawapi.GrowthRatioRequest.
type GrowthRatioRequest = rawapi.GrowthRatioRequest

// GrowthRatioResponse aliases rawapi.GrowthRatioResponse.
type GrowthRatioResponse = rawapi.GrowthRatioResponse

// GrowthRatioOutputItem aliases rawapi.GrowthRatioOutputItem.
type GrowthRatioOutputItem = rawapi.GrowthRatioOutputItem

// CreditByCompanyRequest aliases rawapi.CreditByCompanyRequest.
type CreditByCompanyRequest = rawapi.CreditByCompanyRequest

// CreditByCompanyResponse aliases rawapi.CreditByCompanyResponse.
type CreditByCompanyResponse = rawapi.CreditByCompanyResponse

// CreditByCompanyOutputItem aliases rawapi.CreditByCompanyOutputItem.
type CreditByCompanyOutputItem = rawapi.CreditByCompanyOutputItem

// DividendRequest aliases rawapi.DividendRequest.
type DividendRequest = rawapi.DividendRequest

// DividendResponse aliases rawapi.DividendResponse.
type DividendResponse = rawapi.DividendResponse

// DividendOutput1Item aliases rawapi.DividendOutput1Item.
type DividendOutput1Item = rawapi.DividendOutput1Item

// PurreqRequest aliases rawapi.PurreqRequest.
type PurreqRequest = rawapi.PurreqRequest

// PurreqResponse aliases rawapi.PurreqResponse.
type PurreqResponse = rawapi.PurreqResponse

// PurreqOutput1Item aliases rawapi.PurreqOutput1Item.
type PurreqOutput1Item = rawapi.PurreqOutput1Item

// MergerSplitRequest aliases rawapi.MergerSplitRequest.
type MergerSplitRequest = rawapi.MergerSplitRequest

// MergerSplitResponse aliases rawapi.MergerSplitResponse.
type MergerSplitResponse = rawapi.MergerSplitResponse

// MergerSplitOutput1Item aliases rawapi.MergerSplitOutput1Item.
type MergerSplitOutput1Item = rawapi.MergerSplitOutput1Item

// RevSplitRequest aliases rawapi.RevSplitRequest.
type RevSplitRequest = rawapi.RevSplitRequest

// RevSplitResponse aliases rawapi.RevSplitResponse.
type RevSplitResponse = rawapi.RevSplitResponse

// RevSplitOutput1Item aliases rawapi.RevSplitOutput1Item.
type RevSplitOutput1Item = rawapi.RevSplitOutput1Item

// CapDcrsRequest aliases rawapi.CapDcrsRequest.
type CapDcrsRequest = rawapi.CapDcrsRequest

// CapDcrsResponse aliases rawapi.CapDcrsResponse.
type CapDcrsResponse = rawapi.CapDcrsResponse

// CapDcrsOutput1Item aliases rawapi.CapDcrsOutput1Item.
type CapDcrsOutput1Item = rawapi.CapDcrsOutput1Item

// ListInfoRequest aliases rawapi.ListInfoRequest.
type ListInfoRequest = rawapi.ListInfoRequest

// ListInfoResponse aliases rawapi.ListInfoResponse.
type ListInfoResponse = rawapi.ListInfoResponse

// ListInfoOutput1Item aliases rawapi.ListInfoOutput1Item.
type ListInfoOutput1Item = rawapi.ListInfoOutput1Item

// PubOfferRequest aliases rawapi.PubOfferRequest.
type PubOfferRequest = rawapi.PubOfferRequest

// PubOfferResponse aliases rawapi.PubOfferResponse.
type PubOfferResponse = rawapi.PubOfferResponse

// PubOfferOutput1Item aliases rawapi.PubOfferOutput1Item.
type PubOfferOutput1Item = rawapi.PubOfferOutput1Item

// ForfeitRequest aliases rawapi.ForfeitRequest.
type ForfeitRequest = rawapi.ForfeitRequest

// ForfeitResponse aliases rawapi.ForfeitResponse.
type ForfeitResponse = rawapi.ForfeitResponse

// ForfeitOutput1Item aliases rawapi.ForfeitOutput1Item.
type ForfeitOutput1Item = rawapi.ForfeitOutput1Item

// MandDepositRequest aliases rawapi.MandDepositRequest.
type MandDepositRequest = rawapi.MandDepositRequest

// MandDepositResponse aliases rawapi.MandDepositResponse.
type MandDepositResponse = rawapi.MandDepositResponse

// MandDepositOutput1Item aliases rawapi.MandDepositOutput1Item.
type MandDepositOutput1Item = rawapi.MandDepositOutput1Item

// PaidinCapinRequest aliases rawapi.PaidinCapinRequest.
type PaidinCapinRequest = rawapi.PaidinCapinRequest

// PaidinCapinResponse aliases rawapi.PaidinCapinResponse.
type PaidinCapinResponse = rawapi.PaidinCapinResponse

// PaidinCapinOutputItem aliases rawapi.PaidinCapinOutputItem.
type PaidinCapinOutputItem = rawapi.PaidinCapinOutputItem

// BonusIssueRequest aliases rawapi.BonusIssueRequest.
type BonusIssueRequest = rawapi.BonusIssueRequest

// BonusIssueResponse aliases rawapi.BonusIssueResponse.
type BonusIssueResponse = rawapi.BonusIssueResponse

// BonusIssueOutput1Item aliases rawapi.BonusIssueOutput1Item.
type BonusIssueOutput1Item = rawapi.BonusIssueOutput1Item

// SharehldMeetRequest aliases rawapi.SharehldMeetRequest.
type SharehldMeetRequest = rawapi.SharehldMeetRequest

// SharehldMeetResponse aliases rawapi.SharehldMeetResponse.
type SharehldMeetResponse = rawapi.SharehldMeetResponse

// SharehldMeetOutput1Item aliases rawapi.SharehldMeetOutput1Item.
type SharehldMeetOutput1Item = rawapi.SharehldMeetOutput1Item

// EstimatePerformRequest aliases rawapi.EstimatePerformRequest.
type EstimatePerformRequest = rawapi.EstimatePerformRequest

// EstimatePerformResponse aliases rawapi.EstimatePerformResponse.
type EstimatePerformResponse = rawapi.EstimatePerformResponse

// EstimatePerformOutput1 aliases rawapi.EstimatePerformOutput1.
type EstimatePerformOutput1 = rawapi.EstimatePerformOutput1

// EstimatePerformOutput2Item aliases rawapi.EstimatePerformOutput2Item.
type EstimatePerformOutput2Item = rawapi.EstimatePerformOutput2Item

// EstimatePerformOutput3Item aliases rawapi.EstimatePerformOutput3Item.
type EstimatePerformOutput3Item = rawapi.EstimatePerformOutput3Item

// EstimatePerformOutput4Item aliases rawapi.EstimatePerformOutput4Item.
type EstimatePerformOutput4Item = rawapi.EstimatePerformOutput4Item

// LendableByCompanyRequest aliases rawapi.LendableByCompanyRequest.
type LendableByCompanyRequest = rawapi.LendableByCompanyRequest

// LendableByCompanyResponse aliases rawapi.LendableByCompanyResponse.
type LendableByCompanyResponse = rawapi.LendableByCompanyResponse

// LendableByCompanyOutput1Item aliases rawapi.LendableByCompanyOutput1Item.
type LendableByCompanyOutput1Item = rawapi.LendableByCompanyOutput1Item

// LendableByCompanyOutput2 aliases rawapi.LendableByCompanyOutput2.
type LendableByCompanyOutput2 = rawapi.LendableByCompanyOutput2

// InvestOpinionRequest aliases rawapi.InvestOpinionRequest.
type InvestOpinionRequest = rawapi.InvestOpinionRequest

// InvestOpinionResponse aliases rawapi.InvestOpinionResponse.
type InvestOpinionResponse = rawapi.InvestOpinionResponse

// InvestOpinionOutputItem aliases rawapi.InvestOpinionOutputItem.
type InvestOpinionOutputItem = rawapi.InvestOpinionOutputItem

// InvestOpbysecRequest aliases rawapi.InvestOpbysecRequest.
type InvestOpbysecRequest = rawapi.InvestOpbysecRequest

// InvestOpbysecResponse aliases rawapi.InvestOpbysecResponse.
type InvestOpbysecResponse = rawapi.InvestOpbysecResponse

// InvestOpbysecOutputItem aliases rawapi.InvestOpbysecOutputItem.
type InvestOpbysecOutputItem = rawapi.InvestOpbysecOutputItem
