// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// MarketService calls KIS APIs in the market group.
type MarketService struct {
	executor rawapi.Executor
}

// Market returns the Market service.
func (c *Client) Market() MarketService {
	return MarketService{executor: c.rawAPIExecutor()}
}

// InquireIndexPrice calls the KIS 국내업종 현재지수[v1_국내주식-063] API.
//
// KIS API: 국내업종 현재지수[v1_국내주식-063]
// Summary: 국내업종 현재지수 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0210] 업종 현재지수 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-index-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-index-price
// TR ID: FHPUP02100000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) InquireIndexPrice(ctx context.Context, input InquireIndexPriceRequest) (InquireIndexPriceResponse, error) {
	return rawapi.InquireIndexPrice(ctx, s.executor, input)
}

// InquireIndexDailyPrice calls the KIS 국내업종 일자별지수[v1_국내주식-065] API.
//
// KIS API: 국내업종 일자별지수[v1_국내주식-065]
// Summary: 국내업종 일자별지수 API입니다. 한 번의 조회에 100건까지 확인 가능합니다. 한국투자 HTS(eFriend Plus) &gt; [0212] 업종 일자별지수 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-index-daily-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-index-daily-price
// TR ID: FHPUP02120000
// Virtual TR ID: 모의투자 미지원
// Role hint: daily_bar
func (s MarketService) InquireIndexDailyPrice(ctx context.Context, input InquireIndexDailyPriceRequest) (InquireIndexDailyPriceResponse, error) {
	return rawapi.InquireIndexDailyPrice(ctx, s.executor, input)
}

// InquireIndexTickprice calls the KIS 국내업종 시간별지수(초)[국내주식-064] API.
//
// KIS API: 국내업종 시간별지수(초)[국내주식-064]
// Summary: 국내업종 시간별지수(초) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0211] 업종 시간별지수 화면에서 우측 '10초' 선택 시의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-index-tickprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-index-tickprice
// TR ID: FHPUP02110100
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) InquireIndexTickprice(ctx context.Context, input InquireIndexTickpriceRequest) (InquireIndexTickpriceResponse, error) {
	return rawapi.InquireIndexTickprice(ctx, s.executor, input)
}

// InquireIndexTimeprice calls the KIS 국내업종 시간별지수(분)[국내주식-119] API.
//
// KIS API: 국내업종 시간별지수(분)[국내주식-119]
// Summary: 국내업종 시간별지수(분) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0211] 업종 시간별지수 화면에서 우측 '1분' 선택 시의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-index-timeprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-index-timeprice
// TR ID: FHPUP02110200
// Virtual TR ID: 모의투자 미지원
// Role hint: intraday_bar
func (s MarketService) InquireIndexTimeprice(ctx context.Context, input InquireIndexTimepriceRequest) (InquireIndexTimepriceResponse, error) {
	return rawapi.InquireIndexTimeprice(ctx, s.executor, input)
}

// InquireTimeIndexchartprice calls the KIS 업종 분봉조회[v1_국내주식-045] API.
//
// KIS API: 업종 분봉조회[v1_국내주식-045]
// Summary: 업종 분봉조회 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0350] 업종 종합차트 화면의 분봉기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 실전계좌의 경우, 한 번의 호출에 최대 102건까지 확인 가능합니다.
// Operation ID: inquire-time-indexchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-indexchartprice
// TR ID: FHKUP03500200
// Virtual TR ID: 모의투자 미지원
// Role hint: daily_bar
func (s MarketService) InquireTimeIndexchartprice(ctx context.Context, input InquireTimeIndexchartpriceRequest) (InquireTimeIndexchartpriceResponse, error) {
	return rawapi.InquireTimeIndexchartprice(ctx, s.executor, input)
}

// InquireDailyIndexchartprice calls the KIS 국내주식업종기간별시세(일/주/월/년)[v1_국내주식-021] API.
//
// KIS API: 국내주식업종기간별시세(일/주/월/년)[v1_국내주식-021]
// Summary: 국내주식 업종기간별시세(일/주/월/년) API입니다. 실전계좌/모의계좌의 경우, 한 번의 호출에 최대 50건까지 확인 가능합니다.
// Operation ID: inquire-daily-indexchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-indexchartprice
// TR ID: FHKUP03500100
// Virtual TR ID: FHKUP03500100
// Role hint: daily_bar
func (s MarketService) InquireDailyIndexchartprice(ctx context.Context, input InquireDailyIndexchartpriceRequest) (InquireDailyIndexchartpriceResponse, error) {
	return rawapi.InquireDailyIndexchartprice(ctx, s.executor, input)
}

// InquireIndexCategoryPrice calls the KIS 국내업종 구분별전체시세[v1_국내주식-066] API.
//
// KIS API: 국내업종 구분별전체시세[v1_국내주식-066]
// Summary: 국내업종 구분별전체시세 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0214] 업종 전체시세 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-index-category-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-index-category-price
// TR ID: FHPUP02140000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) InquireIndexCategoryPrice(ctx context.Context, input InquireIndexCategoryPriceRequest) (InquireIndexCategoryPriceResponse, error) {
	return rawapi.InquireIndexCategoryPrice(ctx, s.executor, input)
}

// ExpIndexTrend calls the KIS 국내주식 예상체결지수 추이[국내주식-121] API.
//
// KIS API: 국내주식 예상체결지수 추이[국내주식-121]
// Summary: 국내주식 예상체결지수 추이 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0184] 예상체결지수 추이 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: exp-index-trend
// Endpoint: GET /uapi/domestic-stock/v1/quotations/exp-index-trend
// TR ID: FHPST01840000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) ExpIndexTrend(ctx context.Context, input ExpIndexTrendRequest) (ExpIndexTrendResponse, error) {
	return rawapi.ExpIndexTrend(ctx, s.executor, input)
}

// ExpTotalIndex calls the KIS 국내주식 예상체결 전체지수[국내주식-122] API.
//
// KIS API: 국내주식 예상체결 전체지수[국내주식-122]
// Summary: 국내주식 예상체결 전체지수 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0185] 예상체결 전체지수 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: exp-total-index
// Endpoint: GET /uapi/domestic-stock/v1/quotations/exp-total-index
// TR ID: FHKUP11750000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) ExpTotalIndex(ctx context.Context, input ExpTotalIndexRequest) (ExpTotalIndexResponse, error) {
	return rawapi.ExpTotalIndex(ctx, s.executor, input)
}

// InquireViStatus calls the KIS 변동성완화장치(VI) 현황 [v1_국내주식-055] API.
//
// KIS API: 변동성완화장치(VI) 현황 [v1_국내주식-055]
// Summary: HTS(eFriend Plus) [0139] 변동성 완화장치(VI) 현황 데이터를 확인할 수 있는 API입니다.  최근 30건까지 확인 가능합니다.
// Operation ID: inquire-vi-status
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-vi-status
// TR ID: FHPST01390000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) InquireViStatus(ctx context.Context, input InquireViStatusRequest) (InquireViStatusResponse, error) {
	return rawapi.InquireViStatus(ctx, s.executor, input)
}

// CompInterest calls the KIS 금리 종합(국내채권/금리) [국내주식-155] API.
//
// KIS API: 금리 종합(국내채권/금리) [국내주식-155]
// Summary: 금리 종합(국내채권/금리) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0702] 금리 종합 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 11:30 이후에 신규데이터가 수신되는 점 참고하시기 바랍니다.
// Operation ID: comp-interest
// Endpoint: GET /uapi/domestic-stock/v1/quotations/comp-interest
// TR ID: FHPST07020000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) CompInterest(ctx context.Context, input CompInterestRequest) (CompInterestResponse, error) {
	return rawapi.CompInterest(ctx, s.executor, input)
}

// NewsTitle calls the KIS 종합 시황/공시(제목) [국내주식-141] API.
//
// KIS API: 종합 시황/공시(제목) [국내주식-141]
// Summary: 종합 시황/공시(제목) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0601] 종합 시황/공시 화면의 "우측 상단 리스트" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: news-title
// Endpoint: GET /uapi/domestic-stock/v1/quotations/news-title
// TR ID: FHKST01011800
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) NewsTitle(ctx context.Context, input NewsTitleRequest) (NewsTitleResponse, error) {
	return rawapi.NewsTitle(ctx, s.executor, input)
}

// ChkHoliday calls the KIS 국내휴장일조회[국내주식-040] API.
//
// KIS API: 국내휴장일조회[국내주식-040]
// Summary: (★중요) 국내휴장일조회(TCA0903R) 서비스는 당사 원장서비스와 연관되어 있어  단시간 내 다수 호출시 서비스에 영향을 줄 수 있어 가급적 1일 1회 호출 부탁드립니다.  국내휴장일조회 API입니다. 영업일, 거래일, 개장일, 결제일 여부를 조회할 수 있습니다. 주문을 넣을 수 있는지 확인하고자 하실 경우 개장일여부(opnd_yn)을 사용하시면 됩니다.
// Operation ID: chk-holiday
// Endpoint: GET /uapi/domestic-stock/v1/quotations/chk-holiday
// TR ID: CTCA0903R
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s MarketService) ChkHoliday(ctx context.Context, input ChkHolidayRequest) (ChkHolidayResponse, error) {
	return rawapi.ChkHoliday(ctx, s.executor, input)
}

// MarketTime calls the KIS 국내선물 영업일조회 [국내주식-160] API.
//
// KIS API: 국내선물 영업일조회 [국내주식-160]
// Summary: 국내선물 영업일조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [1938] 시가총액순위 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. API호출 시 body 혹은 params로 입력하는 사항이 없습니다.
// Operation ID: market-time
// Endpoint: GET /uapi/domestic-stock/v1/quotations/market-time
// TR ID: HHMCM000002C0
// Virtual TR ID: 모의투자 미지원
// Role hint: intraday_bar
func (s MarketService) MarketTime(ctx context.Context, input MarketTimeRequest) (MarketTimeResponse, error) {
	return rawapi.MarketTime(ctx, s.executor, input)
}
