// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// QuoteService calls KIS APIs in the quote group.
type QuoteService struct {
	executor rawapi.Executor
}

// Quote returns the Quote service.
func (c *Client) Quote() QuoteService {
	return QuoteService{executor: c.rawAPIExecutor()}
}

// Price calls the KIS 주식현재가 시세[v1_국내주식-008] API.
//
// KIS API: 주식현재가 시세[v1_국내주식-008]
// Summary: 국내 주식 현재가 시세를 조회합니다.
// Operation ID: inquire-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-price
// TR ID: FHKST01010100
// Virtual TR ID: FHKST01010100
// Role hint: quote_snapshot
func (s QuoteService) Price(ctx context.Context, input InquirePriceRequest) (InquirePriceResponse, error) {
	return rawapi.InquirePrice(ctx, s.executor, input)
}

// Trades calls the KIS 주식현재가 체결[v1_국내주식-009] API.
//
// KIS API: 주식현재가 체결[v1_국내주식-009]
// Summary: 국내 주식 현재가 체결 내역을 조회합니다.
// Operation ID: inquire-ccnl
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-ccnl
// TR ID: FHKST01010300
// Virtual TR ID: FHKST01010300
// Role hint: trades
func (s QuoteService) Trades(ctx context.Context, input InquireCcnlRequest) (InquireCcnlResponse, error) {
	return rawapi.InquireCcnl(ctx, s.executor, input)
}

// DailyPrice calls the KIS 주식현재가 일자별[v1_국내주식-010] API.
//
// KIS API: 주식현재가 일자별[v1_국내주식-010]
// Summary: 국내 주식 현재가 일자별 시세를 조회합니다.
// Operation ID: inquire-daily-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-price
// TR ID: FHKST01010400
// Virtual TR ID: FHKST01010400
// Role hint: daily_bar
func (s QuoteService) DailyPrice(ctx context.Context, input InquireDailyPriceRequest) (InquireDailyPriceResponse, error) {
	return rawapi.InquireDailyPrice(ctx, s.executor, input)
}

// Orderbook calls the KIS 주식현재가 호가/예상체결[v1_국내주식-011] API.
//
// KIS API: 주식현재가 호가/예상체결[v1_국내주식-011]
// Summary: 국내 주식 현재가 호가와 예상 체결을 조회합니다.
// Operation ID: inquire-asking-price-exp-ccn
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn
// TR ID: FHKST01010200
// Virtual TR ID: FHKST01010200
// Role hint: orderbook
func (s QuoteService) Orderbook(ctx context.Context, input InquireAskingPriceExpCcnRequest) (InquireAskingPriceExpCcnResponse, error) {
	return rawapi.InquireAskingPriceExpCcn(ctx, s.executor, input)
}

// Investor calls the KIS 주식현재가 투자자[v1_국내주식-012] API.
//
// KIS API: 주식현재가 투자자[v1_국내주식-012]
// Summary: 국내 주식 현재가 투자자 정보를 조회합니다.
// Operation ID: inquire-investor
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-investor
// TR ID: FHKST01010900
// Virtual TR ID: FHKST01010900
// Role hint: market_scan
func (s QuoteService) Investor(ctx context.Context, input InquireInvestorRequest) (InquireInvestorResponse, error) {
	return rawapi.InquireInvestor(ctx, s.executor, input)
}

// Member calls the KIS 주식현재가 회원사[v1_국내주식-013] API.
//
// KIS API: 주식현재가 회원사[v1_국내주식-013]
// Summary: 국내 주식 현재가 회원사 정보를 조회합니다.
// Operation ID: inquire-member
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-member
// TR ID: FHKST01010600
// Virtual TR ID: FHKST01010600
// Role hint: market_scan
func (s QuoteService) Member(ctx context.Context, input InquireMemberRequest) (InquireMemberResponse, error) {
	return rawapi.InquireMember(ctx, s.executor, input)
}

// Daily calls the KIS 국내주식기간별시세(일/주/월/년)[v1_국내주식-016] API.
//
// KIS API: 국내주식기간별시세(일/주/월/년)[v1_국내주식-016]
// Summary: 국내 주식 일별 차트 가격을 조회합니다.
// Operation ID: inquire-daily-itemchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice
// TR ID: FHKST03010100
// Virtual TR ID: FHKST03010100
// Role hint: daily_bar
func (s QuoteService) Daily(ctx context.Context, input InquireDailyItemChartPriceRequest) (InquireDailyItemChartPriceResponse, error) {
	return rawapi.InquireDailyItemChartPrice(ctx, s.executor, input)
}

// Intraday calls the KIS 주식당일분봉조회[v1_국내주식-022] API.
//
// KIS API: 주식당일분봉조회[v1_국내주식-022]
// Summary: 국내 주식 시간대별 차트 가격을 조회합니다.
// Operation ID: inquire-time-itemchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
// TR ID: FHKST03010200
// Virtual TR ID: FHKST03010200
// Role hint: intraday_bar
func (s QuoteService) Intraday(ctx context.Context, input InquireTimeItemChartPriceRequest) (InquireTimeItemChartPriceResponse, error) {
	return rawapi.InquireTimeItemChartPrice(ctx, s.executor, input)
}

// TimeTrades calls the KIS 주식현재가 당일시간대별체결[v1_국내주식-023] API.
//
// KIS API: 주식현재가 당일시간대별체결[v1_국내주식-023]
// Summary: 국내 주식 현재가 당일 시간대별 체결을 조회합니다.
// Operation ID: inquire-time-itemconclusion
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-itemconclusion
// TR ID: FHPST01060000
// Virtual TR ID: FHPST01060000
// Role hint: trades
func (s QuoteService) TimeTrades(ctx context.Context, input InquireTimeItemConclusionRequest) (InquireTimeItemConclusionResponse, error) {
	return rawapi.InquireTimeItemConclusion(ctx, s.executor, input)
}
