// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// InstrumentService calls KIS APIs in the instrument group.
type InstrumentService struct {
	executor rawapi.Executor
}

// Instrument returns the Instrument service.
func (c *Client) Instrument() InstrumentService {
	return InstrumentService{executor: c.rawAPIExecutor()}
}

// Product calls the KIS 상품기본조회[v1_국내주식-029] API.
//
// KIS API: 상품기본조회[v1_국내주식-029]
// Summary: 국내 주식 상품 기본 정보를 조회합니다.
// Operation ID: search-info
// Endpoint: GET /uapi/domestic-stock/v1/quotations/search-info
// TR ID: CTPF1604R
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) Product(ctx context.Context, input SearchInfoRequest) (SearchInfoResponse, error) {
	return rawapi.SearchInfo(ctx, s.executor, input)
}

// Stock calls the KIS 주식기본조회[v1_국내주식-067] API.
//
// KIS API: 주식기본조회[v1_국내주식-067]
// Summary: 국내 주식 종목 기본 정보를 조회합니다.
// Operation ID: search-stock-info
// Endpoint: GET /uapi/domestic-stock/v1/quotations/search-stock-info
// TR ID: CTPF1002R
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) Stock(ctx context.Context, input SearchStockInfoRequest) (SearchStockInfoResponse, error) {
	return rawapi.SearchStockInfo(ctx, s.executor, input)
}

// BalanceSheet calls the KIS 국내주식 대차대조표[v1_국내주식-078] API.
//
// KIS API: 국내주식 대차대조표[v1_국내주식-078]
// Summary: 국내주식 대차대조표 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '1. 대차대조표' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: balance-sheet
// Endpoint: GET /uapi/domestic-stock/v1/finance/balance-sheet
// TR ID: FHKST66430100
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) BalanceSheet(ctx context.Context, input BalanceSheetRequest) (BalanceSheetResponse, error) {
	return rawapi.BalanceSheet(ctx, s.executor, input)
}

// IncomeStatement calls the KIS 국내주식 손익계산서[v1_국내주식-079] API.
//
// KIS API: 국내주식 손익계산서[v1_국내주식-079]
// Summary: 국내주식 손익계산서 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '2. 손익계산서' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: income-statement
// Endpoint: GET /uapi/domestic-stock/v1/finance/income-statement
// TR ID: FHKST66430200
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) IncomeStatement(ctx context.Context, input IncomeStatementRequest) (IncomeStatementResponse, error) {
	return rawapi.IncomeStatement(ctx, s.executor, input)
}

// FinancialRatio calls the KIS 국내주식 재무비율[v1_국내주식-080] API.
//
// KIS API: 국내주식 재무비율[v1_국내주식-080]
// Summary: 국내주식 재무비율 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 우측의 '재무 비율' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: financial-ratio
// Endpoint: GET /uapi/domestic-stock/v1/finance/financial-ratio
// TR ID: FHKST66430300
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) FinancialRatio(ctx context.Context, input FinancialRatioRequest) (FinancialRatioResponse, error) {
	return rawapi.FinancialRatio(ctx, s.executor, input)
}

// ProfitRatio calls the KIS 국내주식 수익성비율[v1_국내주식-081] API.
//
// KIS API: 국내주식 수익성비율[v1_국내주식-081]
// Summary: 국내주식 수익성비율 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '4. 수익성비율' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: profit-ratio
// Endpoint: GET /uapi/domestic-stock/v1/finance/profit-ratio
// TR ID: FHKST66430400
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) ProfitRatio(ctx context.Context, input ProfitRatioRequest) (ProfitRatioResponse, error) {
	return rawapi.ProfitRatio(ctx, s.executor, input)
}

// OtherMajorRatios calls the KIS 국내주식 기타주요비율[v1_국내주식-082] API.
//
// KIS API: 국내주식 기타주요비율[v1_국내주식-082]
// Summary: 국내주식 기타주요비율 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '9. 기타주요비율' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: other-major-ratios
// Endpoint: GET /uapi/domestic-stock/v1/finance/other-major-ratios
// TR ID: FHKST66430500
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) OtherMajorRatios(ctx context.Context, input OtherMajorRatiosRequest) (OtherMajorRatiosResponse, error) {
	return rawapi.OtherMajorRatios(ctx, s.executor, input)
}

// StabilityRatio calls the KIS 국내주식 안정성비율[v1_국내주식-083] API.
//
// KIS API: 국내주식 안정성비율[v1_국내주식-083]
// Summary: 국내주식 안정성비율 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '5. 안정성비율' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: stability-ratio
// Endpoint: GET /uapi/domestic-stock/v1/finance/stability-ratio
// TR ID: FHKST66430600
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) StabilityRatio(ctx context.Context, input StabilityRatioRequest) (StabilityRatioResponse, error) {
	return rawapi.StabilityRatio(ctx, s.executor, input)
}

// GrowthRatio calls the KIS 국내주식 성장성비율[v1_국내주식-085] API.
//
// KIS API: 국내주식 성장성비율[v1_국내주식-085]
// Summary: 국내주식 성장성비율 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0635] 재무분석종합 화면의 하단 '7.성장성비율' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: growth-ratio
// Endpoint: GET /uapi/domestic-stock/v1/finance/growth-ratio
// TR ID: FHKST66430800
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) GrowthRatio(ctx context.Context, input GrowthRatioRequest) (GrowthRatioResponse, error) {
	return rawapi.GrowthRatio(ctx, s.executor, input)
}

// CreditByCompany calls the KIS 국내주식 당사 신용가능종목[국내주식-111] API.
//
// KIS API: 국내주식 당사 신용가능종목[국내주식-111]
// Summary: 국내주식 당사 신용가능종목 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0477] 당사 신용가능 종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 100건 확인 가능하며, 다음 조회가 불가합니다.
// Operation ID: credit-by-company
// Endpoint: GET /uapi/domestic-stock/v1/quotations/credit-by-company
// TR ID: FHPST04770000
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) CreditByCompany(ctx context.Context, input CreditByCompanyRequest) (CreditByCompanyResponse, error) {
	return rawapi.CreditByCompany(ctx, s.executor, input)
}

// Dividend calls the KIS 예탁원정보(배당일정)[국내주식-145] API.
//
// KIS API: 예탁원정보(배당일정)[국내주식-145]
// Summary: 예탁원정보(배당일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0658] 배당 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다. '주식배당지급일'은 배당주식의 주식교부일자를 말합니다. 배당주식의 계좌입고는 배당주식 상장일인데 일반적으로 주권교부일의 익영업일입니다.
// Operation ID: dividend
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/dividend
// TR ID: HHKDB669102C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) Dividend(ctx context.Context, input DividendRequest) (DividendResponse, error) {
	return rawapi.Dividend(ctx, s.executor, input)
}

// Purreq calls the KIS 예탁원정보(주식매수청구일정)[국내주식-146] API.
//
// KIS API: 예탁원정보(주식매수청구일정)[국내주식-146]
// Summary: 예탁원정보(주식매수청구일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0663] 주식매수청구 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: purreq
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/purreq
// TR ID: HHKDB669103C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) Purreq(ctx context.Context, input PurreqRequest) (PurreqResponse, error) {
	return rawapi.Purreq(ctx, s.executor, input)
}

// MergerSplit calls the KIS 예탁원정보(합병/분할일정)[국내주식-147] API.
//
// KIS API: 예탁원정보(합병/분할일정)[국내주식-147]
// Summary: 예탁원정보(합병/분할일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0664] 합병/분할 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: merger-split
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/merger-split
// TR ID: HHKDB669104C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) MergerSplit(ctx context.Context, input MergerSplitRequest) (MergerSplitResponse, error) {
	return rawapi.MergerSplit(ctx, s.executor, input)
}

// RevSplit calls the KIS 예탁원정보(액면교체일정)[국내주식-148] API.
//
// KIS API: 예탁원정보(액면교체일정)[국내주식-148]
// Summary: 예탁원정보(액면교체일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0657] 액면교체 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: rev-split
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/rev-split
// TR ID: HHKDB669105C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) RevSplit(ctx context.Context, input RevSplitRequest) (RevSplitResponse, error) {
	return rawapi.RevSplit(ctx, s.executor, input)
}

// CapDcrs calls the KIS 예탁원정보(자본감소일정)[국내주식-149] API.
//
// KIS API: 예탁원정보(자본감소일정)[국내주식-149]
// Summary: 예탁원정보(자본감소일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0665] 자본감소 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: cap-dcrs
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/cap-dcrs
// TR ID: HHKDB669106C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) CapDcrs(ctx context.Context, input CapDcrsRequest) (CapDcrsResponse, error) {
	return rawapi.CapDcrs(ctx, s.executor, input)
}

// ListInfo calls the KIS 예탁원정보(상장정보일정)[국내주식-150] API.
//
// KIS API: 예탁원정보(상장정보일정)[국내주식-150]
// Summary: 예탁원정보(상장정보일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0666] 상장정보 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: list-info
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/list-info
// TR ID: HHKDB669107C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) ListInfo(ctx context.Context, input ListInfoRequest) (ListInfoResponse, error) {
	return rawapi.ListInfo(ctx, s.executor, input)
}

// PubOffer calls the KIS 예탁원정보(공모주청약일정)[국내주식-151] API.
//
// KIS API: 예탁원정보(공모주청약일정)[국내주식-151]
// Summary: 예탁원정보(공모주청약일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0667] 공모주청약 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: pub-offer
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/pub-offer
// TR ID: HHKDB669108C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) PubOffer(ctx context.Context, input PubOfferRequest) (PubOfferResponse, error) {
	return rawapi.PubOffer(ctx, s.executor, input)
}

// Forfeit calls the KIS 예탁원정보(실권주일정)[국내주식-152] API.
//
// KIS API: 예탁원정보(실권주일정)[국내주식-152]
// Summary: 예탁원정보(실권주일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0668] 실권주 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: forfeit
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/forfeit
// TR ID: HHKDB669109C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) Forfeit(ctx context.Context, input ForfeitRequest) (ForfeitResponse, error) {
	return rawapi.Forfeit(ctx, s.executor, input)
}

// MandDeposit calls the KIS 예탁원정보(의무예치일정)[국내주식-153] API.
//
// KIS API: 예탁원정보(의무예치일정)[국내주식-153]
// Summary: 예탁원정보(의무예치일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0758] 의무예치 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: mand-deposit
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/mand-deposit
// TR ID: HHKDB669110C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) MandDeposit(ctx context.Context, input MandDepositRequest) (MandDepositResponse, error) {
	return rawapi.MandDeposit(ctx, s.executor, input)
}

// PaidinCapin calls the KIS 예탁원정보(유상증자일정) [국내주식-143] API.
//
// KIS API: 예탁원정보(유상증자일정) [국내주식-143]
// Summary: 예탁원정보(유상증자일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0655] 유상증자 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: paidin-capin
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/paidin-capin
// TR ID: HHKDB669100C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) PaidinCapin(ctx context.Context, input PaidinCapinRequest) (PaidinCapinResponse, error) {
	return rawapi.PaidinCapin(ctx, s.executor, input)
}

// BonusIssue calls the KIS 예탁원정보(무상증자일정) [국내주식-144] API.
//
// KIS API: 예탁원정보(무상증자일정) [국내주식-144]
// Summary: 예탁원정보(무상증자일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0656] 무상증자 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: bonus-issue
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/bonus-issue
// TR ID: HHKDB669101C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) BonusIssue(ctx context.Context, input BonusIssueRequest) (BonusIssueResponse, error) {
	return rawapi.BonusIssue(ctx, s.executor, input)
}

// SharehldMeet calls the KIS 예탁원정보(주주총회일정) [국내주식-154] API.
//
// KIS API: 예탁원정보(주주총회일정) [국내주식-154]
// Summary: 예탁원정보(주주총회일정) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0759] 주주총회 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 예탁원에서 제공한 자료이므로 정보용으로만 사용하시기 바랍니다.
// Operation ID: sharehld-meet
// Endpoint: GET /uapi/domestic-stock/v1/ksdinfo/sharehld-meet
// TR ID: HHKDB669111C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) SharehldMeet(ctx context.Context, input SharehldMeetRequest) (SharehldMeetResponse, error) {
	return rawapi.SharehldMeet(ctx, s.executor, input)
}

// EstimatePerform calls the KIS 국내주식 종목추정실적 [국내주식-187] API.
//
// KIS API: 국내주식 종목추정실적 [국내주식-187]
// Summary: 국내주식 종목추정실적 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0613] 종목추정실적 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.    ※ 본 화면의 추정실적 및 투자의견은 당월 초의 애널리스트의 의견사항이므로 월중 변동 사항이 있을 수 있음을 유의하시기 바랍니다. ※ 종목별 수익추정은 리서치본부에서 매월 발표되는 거래소, 코스닥 160여개 기업에 한정합니다. 구체적인 종목 리스트는 추정종목리스트를 참고하기 바랍니다.
// Operation ID: estimate-perform
// Endpoint: GET /uapi/domestic-stock/v1/quotations/estimate-perform
// TR ID: HHKST668300C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) EstimatePerform(ctx context.Context, input EstimatePerformRequest) (EstimatePerformResponse, error) {
	return rawapi.EstimatePerform(ctx, s.executor, input)
}

// LendableByCompany calls the KIS 당사 대주가능 종목 [국내주식-195] API.
//
// KIS API: 당사 대주가능 종목 [국내주식-195]
// Summary: 당사 대주가능 종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0490] 당사 대주가능 종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 본 API는 다음조회가 불가합니다.
// Operation ID: lendable-by-company
// Endpoint: GET /uapi/domestic-stock/v1/quotations/lendable-by-company
// TR ID: CTSC2702R
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) LendableByCompany(ctx context.Context, input LendableByCompanyRequest) (LendableByCompanyResponse, error) {
	return rawapi.LendableByCompany(ctx, s.executor, input)
}

// InvestOpinion calls the KIS 국내주식 종목투자의견 [국내주식-188] API.
//
// KIS API: 국내주식 종목투자의견 [국내주식-188]
// Summary: 국내주식 종목투자의견 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0605] 종목투자의견 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  한 번의 호출에 100건까지 조회가 가능하기에, 일자 파라미터(FID_INPUT_DATE_1, FID_INPUT_DATE_2)를 조절하여 다음 데이터 조회하시기 바랍니다.
// Operation ID: invest-opinion
// Endpoint: GET /uapi/domestic-stock/v1/quotations/invest-opinion
// TR ID: FHKST663300C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) InvestOpinion(ctx context.Context, input InvestOpinionRequest) (InvestOpinionResponse, error) {
	return rawapi.InvestOpinion(ctx, s.executor, input)
}

// InvestOpbysec calls the KIS 국내주식 증권사별 투자의견 [국내주식-189] API.
//
// KIS API: 국내주식 증권사별 투자의견 [국내주식-189]
// Summary: 국내주식 증권사별 투자의견 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0608] 증권사별 투자의견 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  한 번의 호출에 20건까지 조회가 가능하기에, 일자 파라미터(FID_INPUT_DATE_1, FID_INPUT_DATE_2)를 조절하여 다음 데이터 조회하시기 바랍니다.
// Operation ID: invest-opbysec
// Endpoint: GET /uapi/domestic-stock/v1/quotations/invest-opbysec
// TR ID: FHKST663400C0
// Virtual TR ID: 모의투자 미지원
// Role hint: instrument
func (s InstrumentService) InvestOpbysec(ctx context.Context, input InvestOpbysecRequest) (InvestOpbysecResponse, error) {
	return rawapi.InvestOpbysec(ctx, s.executor, input)
}
