// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// RankingService calls KIS APIs in the ranking group.
type RankingService struct {
	executor rawapi.Executor
}

// Ranking returns the Ranking service.
func (c *Client) Ranking() RankingService {
	return RankingService{executor: c.rawAPIExecutor()}
}

// Volume calls the KIS 거래량순위[v1_국내주식-047] API.
//
// KIS API: 거래량순위[v1_국내주식-047]
// Summary: 국내 주식 거래량 순위를 조회합니다.
// Operation ID: volume-rank
// Endpoint: GET /uapi/domestic-stock/v1/quotations/volume-rank
// TR ID: FHPST01710000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) Volume(ctx context.Context, input VolumeRankRequest) (VolumeRankResponse, error) {
	return rawapi.VolumeRank(ctx, s.executor, input)
}

// Fluctuation calls the KIS 국내주식 등락률 순위[v1_국내주식-088] API.
//
// KIS API: 국내주식 등락률 순위[v1_국내주식-088]
// Summary: 국내 주식 등락률 순위를 조회합니다.
// Operation ID: fluctuation
// Endpoint: GET /uapi/domestic-stock/v1/ranking/fluctuation
// TR ID: FHPST01700000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) Fluctuation(ctx context.Context, input FluctuationRequest) (FluctuationResponse, error) {
	return rawapi.Fluctuation(ctx, s.executor, input)
}

// QuoteBalance calls the KIS 국내주식 호가잔량 순위[국내주식-089] API.
//
// KIS API: 국내주식 호가잔량 순위[국내주식-089]
// Summary: 국내주식 호가잔량 순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0172] 호가잔량 순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: quote-balance
// Endpoint: GET /uapi/domestic-stock/v1/ranking/quote-balance
// TR ID: FHPST01720000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) QuoteBalance(ctx context.Context, input QuoteBalanceRequest) (QuoteBalanceResponse, error) {
	return rawapi.QuoteBalance(ctx, s.executor, input)
}

// ProfitAssetIndex calls the KIS 국내주식 수익자산지표 순위[v1_국내주식-090] API.
//
// KIS API: 국내주식 수익자산지표 순위[v1_국내주식-090]
// Summary: 국내주식 수익자산지표 순위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0173] 수익자산지표 순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: profit-asset-index
// Endpoint: GET /uapi/domestic-stock/v1/ranking/profit-asset-index
// TR ID: FHPST01730000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) ProfitAssetIndex(ctx context.Context, input ProfitAssetIndexRequest) (ProfitAssetIndexResponse, error) {
	return rawapi.ProfitAssetIndex(ctx, s.executor, input)
}

// MarketCap calls the KIS 국내주식 시가총액 상위[v1_국내주식-091] API.
//
// KIS API: 국내주식 시가총액 상위[v1_국내주식-091]
// Summary: 국내 주식 시가총액 상위 순위를 조회합니다.
// Operation ID: market-cap
// Endpoint: GET /uapi/domestic-stock/v1/ranking/market-cap
// TR ID: FHPST01740000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) MarketCap(ctx context.Context, input MarketCapRequest) (MarketCapResponse, error) {
	return rawapi.MarketCap(ctx, s.executor, input)
}

// FinanceRatio calls the KIS 국내주식 재무비율 순위[v1_국내주식-092] API.
//
// KIS API: 국내주식 재무비율 순위[v1_국내주식-092]
// Summary: 국내주식 재무비율 순위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0175] 재무비율순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: finance-ratio
// Endpoint: GET /uapi/domestic-stock/v1/ranking/finance-ratio
// TR ID: FHPST01750000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) FinanceRatio(ctx context.Context, input FinanceRatioRequest) (FinanceRatioResponse, error) {
	return rawapi.FinanceRatio(ctx, s.executor, input)
}

// AfterHourBalance calls the KIS 국내주식 시간외잔량 순위[v1_국내주식-093] API.
//
// KIS API: 국내주식 시간외잔량 순위[v1_국내주식-093]
// Summary: 국내주식 시간외잔량 순위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0176] 시간외잔량 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: after-hour-balance
// Endpoint: GET /uapi/domestic-stock/v1/ranking/after-hour-balance
// TR ID: FHPST01760000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) AfterHourBalance(ctx context.Context, input AfterHourBalanceRequest) (AfterHourBalanceResponse, error) {
	return rawapi.AfterHourBalance(ctx, s.executor, input)
}

// PreferDisparateRatio calls the KIS 국내주식 우선주/괴리율 상위[v1_국내주식-094] API.
//
// KIS API: 국내주식 우선주/괴리율 상위[v1_국내주식-094]
// Summary: 국내주식 우선주/괴리율 상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0177] 우선주/괴리율 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: prefer-disparate-ratio
// Endpoint: GET /uapi/domestic-stock/v1/ranking/prefer-disparate-ratio
// TR ID: FHPST01770000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) PreferDisparateRatio(ctx context.Context, input PreferDisparateRatioRequest) (PreferDisparateRatioResponse, error) {
	return rawapi.PreferDisparateRatio(ctx, s.executor, input)
}

// Disparity calls the KIS 국내주식 이격도 순위[v1_국내주식-095] API.
//
// KIS API: 국내주식 이격도 순위[v1_국내주식-095]
// Summary: 국내주식 이격도 순위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0178] 이격도 순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: disparity
// Endpoint: GET /uapi/domestic-stock/v1/ranking/disparity
// TR ID: FHPST01780000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) Disparity(ctx context.Context, input DisparityRequest) (DisparityResponse, error) {
	return rawapi.Disparity(ctx, s.executor, input)
}

// MarketValue calls the KIS 국내주식 시장가치 순위[v1_국내주식-096] API.
//
// KIS API: 국내주식 시장가치 순위[v1_국내주식-096]
// Summary: 국내 주식 시장가치 순위를 조회합니다.
// Operation ID: market-value
// Endpoint: GET /uapi/domestic-stock/v1/ranking/market-value
// TR ID: FHPST01790000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) MarketValue(ctx context.Context, input MarketValueRequest) (MarketValueResponse, error) {
	return rawapi.MarketValue(ctx, s.executor, input)
}

// VolumePower calls the KIS 국내주식 체결강도 상위[v1_국내주식-101] API.
//
// KIS API: 국내주식 체결강도 상위[v1_국내주식-101]
// Summary: 국내 주식 체결강도 상위 순위를 조회합니다.
// Operation ID: volume-power
// Endpoint: GET /uapi/domestic-stock/v1/ranking/volume-power
// TR ID: FHPST01680000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) VolumePower(ctx context.Context, input VolumePowerRequest) (VolumePowerResponse, error) {
	return rawapi.VolumePower(ctx, s.executor, input)
}

// TopInterestStock calls the KIS 국내주식 관심종목등록 상위[v1_국내주식-102] API.
//
// KIS API: 국내주식 관심종목등록 상위[v1_국내주식-102]
// Summary: 국내주식 관심종목등록 상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0180] 관심종목등록상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: top-interest-stock
// Endpoint: GET /uapi/domestic-stock/v1/ranking/top-interest-stock
// TR ID: FHPST01800000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) TopInterestStock(ctx context.Context, input TopInterestStockRequest) (TopInterestStockResponse, error) {
	return rawapi.TopInterestStock(ctx, s.executor, input)
}

// ExpTransUpdown calls the KIS 국내주식 예상체결 상승/하락상위[v1_국내주식-103] API.
//
// KIS API: 국내주식 예상체결 상승/하락상위[v1_국내주식-103]
// Summary: 국내주식 예상체결 상승/하락상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0182] 예상체결 상승/하락상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: exp-trans-updown
// Endpoint: GET /uapi/domestic-stock/v1/ranking/exp-trans-updown
// TR ID: FHPST01820000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) ExpTransUpdown(ctx context.Context, input ExpTransUpdownRequest) (ExpTransUpdownResponse, error) {
	return rawapi.ExpTransUpdown(ctx, s.executor, input)
}

// TradedByCompany calls the KIS 국내주식 당사매매종목 상위[v1_국내주식-104] API.
//
// KIS API: 국내주식 당사매매종목 상위[v1_국내주식-104]
// Summary: 국내주식 당사매매종목 상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0186] 당사매매종목 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: traded-by-company
// Endpoint: GET /uapi/domestic-stock/v1/ranking/traded-by-company
// TR ID: FHPST01860000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) TradedByCompany(ctx context.Context, input TradedByCompanyRequest) (TradedByCompanyResponse, error) {
	return rawapi.TradedByCompany(ctx, s.executor, input)
}

// NearNewHighlow calls the KIS 국내주식 신고/신저근접종목 상위[v1_국내주식-105] API.
//
// KIS API: 국내주식 신고/신저근접종목 상위[v1_국내주식-105]
// Summary: 국내주식 신고/신저근접종목 상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0187] 신고/신저 근접종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: near-new-highlow
// Endpoint: GET /uapi/domestic-stock/v1/ranking/near-new-highlow
// TR ID: FHPST01870000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) NearNewHighlow(ctx context.Context, input NearNewHighlowRequest) (NearNewHighlowResponse, error) {
	return rawapi.NearNewHighlow(ctx, s.executor, input)
}

// DividendRate calls the KIS 국내주식 배당률 상위[국내주식-106] API.
//
// KIS API: 국내주식 배당률 상위[국내주식-106]
// Summary: 국내주식 배당률 상위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0188] 배당률 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: dividend-rate
// Endpoint: GET /uapi/domestic-stock/v1/ranking/dividend-rate
// TR ID: HHKDB13470100
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) DividendRate(ctx context.Context, input DividendRateRequest) (DividendRateResponse, error) {
	return rawapi.DividendRate(ctx, s.executor, input)
}

// BulkTransNum calls the KIS 국내주식 대량체결건수 상위[국내주식-107] API.
//
// KIS API: 국내주식 대량체결건수 상위[국내주식-107]
// Summary: 국내주식 대량체결건수 상위 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0169] 대량체결건수 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: bulk-trans-num
// Endpoint: GET /uapi/domestic-stock/v1/ranking/bulk-trans-num
// TR ID: FHKST190900C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) BulkTransNum(ctx context.Context, input BulkTransNumRequest) (BulkTransNumResponse, error) {
	return rawapi.BulkTransNum(ctx, s.executor, input)
}

// CreditBalance calls the KIS 국내주식 신용잔고 상위[국내주식-109] API.
//
// KIS API: 국내주식 신용잔고 상위[국내주식-109]
// Summary: 국내주식 신용잔고 상위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0475] 신용잔고 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: credit-balance
// Endpoint: GET /uapi/domestic-stock/v1/ranking/credit-balance
// TR ID: FHKST17010000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) CreditBalance(ctx context.Context, input CreditBalanceRequest) (CreditBalanceResponse, error) {
	return rawapi.CreditBalance(ctx, s.executor, input)
}

// ShortSale calls the KIS 국내주식 공매도 상위종목[국내주식-133] API.
//
// KIS API: 국내주식 공매도 상위종목[국내주식-133]
// Summary: 공매도 상위종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0482] 공매도 상위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.  ※ 30건 이상의 목록 조회가 필요한 경우, 대안으로 종목조건검색 API를 이용해서 원하는 종목 100개까지 검색할 수 있는 기능을 제공하고 있습니다. 종목조건검색 API는 HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API로, 자세한 사용 방법은 공지사항 - [조건검색 필독] 조건검색 API 이용안내 참고 부탁드립니다.
// Operation ID: short-sale
// Endpoint: GET /uapi/domestic-stock/v1/ranking/short-sale
// TR ID: FHPST04820000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) ShortSale(ctx context.Context, input ShortSaleRequest) (ShortSaleResponse, error) {
	return rawapi.ShortSale(ctx, s.executor, input)
}

// OvertimeFluctuation calls the KIS 국내주식 시간외등락율순위 [국내주식-138] API.
//
// KIS API: 국내주식 시간외등락율순위 [국내주식-138]
// Summary: 국내주식 시간외등락율순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0234] 시간외 등락률순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.
// Operation ID: overtime-fluctuation
// Endpoint: GET /uapi/domestic-stock/v1/ranking/overtime-fluctuation
// TR ID: FHPST02340000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) OvertimeFluctuation(ctx context.Context, input OvertimeFluctuationRequest) (OvertimeFluctuationResponse, error) {
	return rawapi.OvertimeFluctuation(ctx, s.executor, input)
}

// OvertimeVolume calls the KIS 국내주식 시간외거래량순위 [국내주식-139] API.
//
// KIS API: 국내주식 시간외거래량순위 [국내주식-139]
// Summary: 국내주식 시간외거래량순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0235] 시간외 거래량순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.
// Operation ID: overtime-volume
// Endpoint: GET /uapi/domestic-stock/v1/ranking/overtime-volume
// TR ID: FHPST02350000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) OvertimeVolume(ctx context.Context, input OvertimeVolumeRequest) (OvertimeVolumeResponse, error) {
	return rawapi.OvertimeVolume(ctx, s.executor, input)
}

// HtsTopView calls the KIS HTS조회상위20종목 [국내주식-214] API.
//
// KIS API: HTS조회상위20종목 [국내주식-214]
// Summary: HTS조회상위20종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0158] 조회종목상위 화면의 "종목명", "종목코드" 표시 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: hts-top-view
// Endpoint: GET /uapi/domestic-stock/v1/ranking/hts-top-view
// TR ID: HHMCM000100C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) HtsTopView(ctx context.Context, input HtsTopViewRequest) (HtsTopViewResponse, error) {
	return rawapi.HtsTopView(ctx, s.executor, input)
}
