// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// RankingService calls KIS APIs in the ranking group.
type RankingService struct {
	executor rawapi.Executor
}

// Ranking returns the Ranking service.
func (c *Client) Ranking() RankingService {
	return RankingService{executor: c.rawAPIExecutor()}
}

// Volume calls the KIS 거래량순위[v1_국내주식-047] API.
//
// KIS API: 거래량순위[v1_국내주식-047]
// Summary: 국내 주식 거래량 순위를 조회합니다.
// Operation ID: volume-rank
// Endpoint: GET /uapi/domestic-stock/v1/quotations/volume-rank
// TR ID: FHPST01710000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) Volume(ctx context.Context, input VolumeRankRequest) (VolumeRankResponse, error) {
	return rawapi.VolumeRank(ctx, s.executor, input)
}

// Fluctuation calls the KIS 국내주식 등락률 순위[v1_국내주식-088] API.
//
// KIS API: 국내주식 등락률 순위[v1_국내주식-088]
// Summary: 국내 주식 등락률 순위를 조회합니다.
// Operation ID: fluctuation
// Endpoint: GET /uapi/domestic-stock/v1/ranking/fluctuation
// TR ID: FHPST01700000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) Fluctuation(ctx context.Context, input FluctuationRequest) (FluctuationResponse, error) {
	return rawapi.Fluctuation(ctx, s.executor, input)
}

// MarketCap calls the KIS 국내주식 시가총액 상위[v1_국내주식-091] API.
//
// KIS API: 국내주식 시가총액 상위[v1_국내주식-091]
// Summary: 국내 주식 시가총액 상위 순위를 조회합니다.
// Operation ID: market-cap
// Endpoint: GET /uapi/domestic-stock/v1/ranking/market-cap
// TR ID: FHPST01740000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) MarketCap(ctx context.Context, input MarketCapRequest) (MarketCapResponse, error) {
	return rawapi.MarketCap(ctx, s.executor, input)
}

// MarketValue calls the KIS 국내주식 시장가치 순위[v1_국내주식-096] API.
//
// KIS API: 국내주식 시장가치 순위[v1_국내주식-096]
// Summary: 국내 주식 시장가치 순위를 조회합니다.
// Operation ID: market-value
// Endpoint: GET /uapi/domestic-stock/v1/ranking/market-value
// TR ID: FHPST01790000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) MarketValue(ctx context.Context, input MarketValueRequest) (MarketValueResponse, error) {
	return rawapi.MarketValue(ctx, s.executor, input)
}

// VolumePower calls the KIS 국내주식 체결강도 상위[v1_국내주식-101] API.
//
// KIS API: 국내주식 체결강도 상위[v1_국내주식-101]
// Summary: 국내 주식 체결강도 상위 순위를 조회합니다.
// Operation ID: volume-power
// Endpoint: GET /uapi/domestic-stock/v1/ranking/volume-power
// TR ID: FHPST01680000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s RankingService) VolumePower(ctx context.Context, input VolumePowerRequest) (VolumePowerResponse, error) {
	return rawapi.VolumePower(ctx, s.executor, input)
}
