// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// QuoteService calls KIS APIs in the quote group.
type QuoteService struct {
	executor rawapi.Executor
}

// Quote returns the Quote service.
func (c *Client) Quote() QuoteService {
	return QuoteService{executor: c.rawAPIExecutor()}
}

// Price calls the KIS 주식현재가 시세[v1_국내주식-008] API.
//
// KIS API: 주식현재가 시세[v1_국내주식-008]
// Summary: 국내 주식 현재가 시세를 조회합니다.
// Operation ID: inquire-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-price
// TR ID: FHKST01010100
// Virtual TR ID: FHKST01010100
// Role hint: quote_snapshot
func (s QuoteService) Price(ctx context.Context, input InquirePriceRequest) (InquirePriceResponse, error) {
	return rawapi.InquirePrice(ctx, s.executor, input)
}

// InquirePrice2 calls the KIS 주식현재가 시세2[v1_국내주식-054] API.
//
// KIS API: 주식현재가 시세2[v1_국내주식-054]
// Summary: 주식현재가 시세2 API입니다.
// Operation ID: inquire-price-2
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-price-2
// TR ID: FHPST01010000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) InquirePrice2(ctx context.Context, input InquirePrice2Request) (InquirePrice2Response, error) {
	return rawapi.InquirePrice2(ctx, s.executor, input)
}

// Trades calls the KIS 주식현재가 체결[v1_국내주식-009] API.
//
// KIS API: 주식현재가 체결[v1_국내주식-009]
// Summary: 국내 주식 현재가 체결 내역을 조회합니다.
// Operation ID: inquire-ccnl
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-ccnl
// TR ID: FHKST01010300
// Virtual TR ID: FHKST01010300
// Role hint: trades
func (s QuoteService) Trades(ctx context.Context, input InquireCcnlRequest) (InquireCcnlResponse, error) {
	return rawapi.InquireCcnl(ctx, s.executor, input)
}

// DailyPrice calls the KIS 주식현재가 일자별[v1_국내주식-010] API.
//
// KIS API: 주식현재가 일자별[v1_국내주식-010]
// Summary: 국내 주식 현재가 일자별 시세를 조회합니다.
// Operation ID: inquire-daily-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-price
// TR ID: FHKST01010400
// Virtual TR ID: FHKST01010400
// Role hint: daily_bar
func (s QuoteService) DailyPrice(ctx context.Context, input InquireDailyPriceRequest) (InquireDailyPriceResponse, error) {
	return rawapi.InquireDailyPrice(ctx, s.executor, input)
}

// Orderbook calls the KIS 주식현재가 호가/예상체결[v1_국내주식-011] API.
//
// KIS API: 주식현재가 호가/예상체결[v1_국내주식-011]
// Summary: 국내 주식 현재가 호가와 예상 체결을 조회합니다.
// Operation ID: inquire-asking-price-exp-ccn
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn
// TR ID: FHKST01010200
// Virtual TR ID: FHKST01010200
// Role hint: orderbook
func (s QuoteService) Orderbook(ctx context.Context, input InquireAskingPriceExpCcnRequest) (InquireAskingPriceExpCcnResponse, error) {
	return rawapi.InquireAskingPriceExpCcn(ctx, s.executor, input)
}

// Investor calls the KIS 주식현재가 투자자[v1_국내주식-012] API.
//
// KIS API: 주식현재가 투자자[v1_국내주식-012]
// Summary: 국내 주식 현재가 투자자 정보를 조회합니다.
// Operation ID: inquire-investor
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-investor
// TR ID: FHKST01010900
// Virtual TR ID: FHKST01010900
// Role hint: market_scan
func (s QuoteService) Investor(ctx context.Context, input InquireInvestorRequest) (InquireInvestorResponse, error) {
	return rawapi.InquireInvestor(ctx, s.executor, input)
}

// Member calls the KIS 주식현재가 회원사[v1_국내주식-013] API.
//
// KIS API: 주식현재가 회원사[v1_국내주식-013]
// Summary: 국내 주식 현재가 회원사 정보를 조회합니다.
// Operation ID: inquire-member
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-member
// TR ID: FHKST01010600
// Virtual TR ID: FHKST01010600
// Role hint: market_scan
func (s QuoteService) Member(ctx context.Context, input InquireMemberRequest) (InquireMemberResponse, error) {
	return rawapi.InquireMember(ctx, s.executor, input)
}

// Daily calls the KIS 국내주식기간별시세(일/주/월/년)[v1_국내주식-016] API.
//
// KIS API: 국내주식기간별시세(일/주/월/년)[v1_국내주식-016]
// Summary: 국내 주식 일별 차트 가격을 조회합니다.
// Operation ID: inquire-daily-itemchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice
// TR ID: FHKST03010100
// Virtual TR ID: FHKST03010100
// Role hint: daily_bar
func (s QuoteService) Daily(ctx context.Context, input InquireDailyItemChartPriceRequest) (InquireDailyItemChartPriceResponse, error) {
	return rawapi.InquireDailyItemChartPrice(ctx, s.executor, input)
}

// Intraday calls the KIS 주식당일분봉조회[v1_국내주식-022] API.
//
// KIS API: 주식당일분봉조회[v1_국내주식-022]
// Summary: 국내 주식 시간대별 차트 가격을 조회합니다.
// Operation ID: inquire-time-itemchartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
// TR ID: FHKST03010200
// Virtual TR ID: FHKST03010200
// Role hint: intraday_bar
func (s QuoteService) Intraday(ctx context.Context, input InquireTimeItemChartPriceRequest) (InquireTimeItemChartPriceResponse, error) {
	return rawapi.InquireTimeItemChartPrice(ctx, s.executor, input)
}

// InquireTimeDailychartprice calls the KIS 주식일별분봉조회 [국내주식-213] API.
//
// KIS API: 주식일별분봉조회 [국내주식-213]
// Summary: 주식일별분봉조회 API입니다.   실전계좌의 경우, 한 번의 호출에 최대 120건까지 확인 가능하며,  FID_INPUT_DATE_1, FID_INPUT_HOUR_1 이용하여 과거일자 분봉조회 가능합니다.  ※ 과거 분봉 조회 시, 당사 서버에서 보관하고 있는 만큼의 데이터만 확인이 가능합니다. (최대 1년 분봉 보관)
// Operation ID: inquire-time-dailychartprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-dailychartprice
// TR ID: FHKST03010230
// Virtual TR ID: 모의투자 미지원
// Role hint: daily_bar
func (s QuoteService) InquireTimeDailychartprice(ctx context.Context, input InquireTimeDailychartpriceRequest) (InquireTimeDailychartpriceResponse, error) {
	return rawapi.InquireTimeDailychartprice(ctx, s.executor, input)
}

// TimeTrades calls the KIS 주식현재가 당일시간대별체결[v1_국내주식-023] API.
//
// KIS API: 주식현재가 당일시간대별체결[v1_국내주식-023]
// Summary: 국내 주식 현재가 당일 시간대별 체결을 조회합니다.
// Operation ID: inquire-time-itemconclusion
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-itemconclusion
// TR ID: FHPST01060000
// Virtual TR ID: FHPST01060000
// Role hint: trades
func (s QuoteService) TimeTrades(ctx context.Context, input InquireTimeItemConclusionRequest) (InquireTimeItemConclusionResponse, error) {
	return rawapi.InquireTimeItemConclusion(ctx, s.executor, input)
}

// InquireDailyOvertimeprice calls the KIS 주식현재가 시간외일자별주가[v1_국내주식-026] API.
//
// KIS API: 주식현재가 시간외일자별주가[v1_국내주식-026]
// Summary: 주식현재가 시간외일자별주가 API입니다.  (최근일 30건만 조회 가능) 한국투자 HTS(eFriend Plus) &gt; [0232] 시간외 일자별주가의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-daily-overtimeprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-overtimeprice
// TR ID: FHPST02320000
// Virtual TR ID: FHPST02320000
// Role hint: intraday_bar
func (s QuoteService) InquireDailyOvertimeprice(ctx context.Context, input InquireDailyOvertimepriceRequest) (InquireDailyOvertimepriceResponse, error) {
	return rawapi.InquireDailyOvertimeprice(ctx, s.executor, input)
}

// InquireTimeOvertimeconclusion calls the KIS 주식현재가 시간외시간별체결[v1_국내주식-025] API.
//
// KIS API: 주식현재가 시간외시간별체결[v1_국내주식-025]
// Summary: 주식현재가 시간외시간별체결 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0231] 시간외 시간별체결의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-time-overtimeconclusion
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-time-overtimeconclusion
// TR ID: FHPST02310000
// Virtual TR ID: FHPST02310000
// Role hint: intraday_bar
func (s QuoteService) InquireTimeOvertimeconclusion(ctx context.Context, input InquireTimeOvertimeconclusionRequest) (InquireTimeOvertimeconclusionResponse, error) {
	return rawapi.InquireTimeOvertimeconclusion(ctx, s.executor, input)
}

// InquireOvertimePrice calls the KIS 국내주식 시간외현재가[국내주식-076] API.
//
// KIS API: 국내주식 시간외현재가[국내주식-076]
// Summary: 국내주식 시간외현재가 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0230] 시간외 현재가 화면의 좌측 상단기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-overtime-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-overtime-price
// TR ID: FHPST02300000
// Virtual TR ID: 모의투자 미지원
// Role hint: intraday_bar
func (s QuoteService) InquireOvertimePrice(ctx context.Context, input InquireOvertimePriceRequest) (InquireOvertimePriceResponse, error) {
	return rawapi.InquireOvertimePrice(ctx, s.executor, input)
}

// InquireOvertimeAskingPrice calls the KIS 국내주식 시간외호가[국내주식-077] API.
//
// KIS API: 국내주식 시간외호가[국내주식-077]
// Summary: 국내주식 시간외호가 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0230] 시간외 현재가 화면의 '호가' 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-overtime-asking-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-overtime-asking-price
// TR ID: FHPST02300400
// Virtual TR ID: 모의투자 미지원
// Role hint: intraday_bar
func (s QuoteService) InquireOvertimeAskingPrice(ctx context.Context, input InquireOvertimeAskingPriceRequest) (InquireOvertimeAskingPriceResponse, error) {
	return rawapi.InquireOvertimeAskingPrice(ctx, s.executor, input)
}

// ExpClosingPrice calls the KIS 국내주식 장마감 예상체결가[국내주식-120] API.
//
// KIS API: 국내주식 장마감 예상체결가[국내주식-120]
// Summary: 국내주식 장마감 예상체결가 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0183] 장마감 예상체결가 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: exp-closing-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/exp-closing-price
// TR ID: FHKST117300C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) ExpClosingPrice(ctx context.Context, input ExpClosingPriceRequest) (ExpClosingPriceResponse, error) {
	return rawapi.ExpClosingPrice(ctx, s.executor, input)
}

// ETFETNQuotationsInquirePrice calls the KIS ETF/ETN 현재가[v1_국내주식-068] API.
//
// KIS API: ETF/ETN 현재가[v1_국내주식-068]
// Summary: ETF/ETN 현재가 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0240] ETF/ETN 현재가 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: etfetn-quotations-inquire-price
// Endpoint: GET /uapi/etfetn/v1/quotations/inquire-price
// TR ID: FHPST02400000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) ETFETNQuotationsInquirePrice(ctx context.Context, input ETFETNQuotationsInquirePriceRequest) (ETFETNQuotationsInquirePriceResponse, error) {
	return rawapi.ETFETNQuotationsInquirePrice(ctx, s.executor, input)
}

// InquireComponentStockPrice calls the KIS ETF 구성종목시세[국내주식-073] API.
//
// KIS API: ETF 구성종목시세[국내주식-073]
// Summary: ETF 구성종목시세 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0245] ETF/ETN 구성종목시세 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-component-stock-price
// Endpoint: GET /uapi/etfetn/v1/quotations/inquire-component-stock-price
// TR ID: FHKST121600C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) InquireComponentStockPrice(ctx context.Context, input InquireComponentStockPriceRequest) (InquireComponentStockPriceResponse, error) {
	return rawapi.InquireComponentStockPrice(ctx, s.executor, input)
}

// NavComparisonTrend calls the KIS NAV 비교추이(종목)[v1_국내주식-069] API.
//
// KIS API: NAV 비교추이(종목)[v1_국내주식-069]
// Summary: NAV 비교추이(종목) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0244] ETF/ETN 비교추이(NAV/IIV) 좌측 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: nav-comparison-trend
// Endpoint: GET /uapi/etfetn/v1/quotations/nav-comparison-trend
// TR ID: FHPST02440000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) NavComparisonTrend(ctx context.Context, input NavComparisonTrendRequest) (NavComparisonTrendResponse, error) {
	return rawapi.NavComparisonTrend(ctx, s.executor, input)
}

// NavComparisonDailyTrend calls the KIS NAV 비교추이(일)[v1_국내주식-071] API.
//
// KIS API: NAV 비교추이(일)[v1_국내주식-071]
// Summary: NAV 비교추이(일) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0244] ETF/ETN 비교추이(NAV/IIV) 좌측 화면 "일별" 비교추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 실전계좌의 경우, 한 번의 호출에 최대 100건까지 확인 가능합니다.
// Operation ID: nav-comparison-daily-trend
// Endpoint: GET /uapi/etfetn/v1/quotations/nav-comparison-daily-trend
// TR ID: FHPST02440200
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s QuoteService) NavComparisonDailyTrend(ctx context.Context, input NavComparisonDailyTrendRequest) (NavComparisonDailyTrendResponse, error) {
	return rawapi.NavComparisonDailyTrend(ctx, s.executor, input)
}

// NavComparisonTimeTrend calls the KIS NAV 비교추이(분)[v1_국내주식-070] API.
//
// KIS API: NAV 비교추이(분)[v1_국내주식-070]
// Summary: NAV 비교추이(분) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0244] ETF/ETN 비교추이(NAV/IIV) 좌측 화면 "분별" 비교추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 실전계좌의 경우, 한 번의 호출에 최근 30건까지 확인 가능합니다.
// Operation ID: nav-comparison-time-trend
// Endpoint: GET /uapi/etfetn/v1/quotations/nav-comparison-time-trend
// TR ID: FHPST02440100
// Virtual TR ID: 모의투자 미지원
// Role hint: intraday_bar
func (s QuoteService) NavComparisonTimeTrend(ctx context.Context, input NavComparisonTimeTrendRequest) (NavComparisonTimeTrendResponse, error) {
	return rawapi.NavComparisonTimeTrend(ctx, s.executor, input)
}
