// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// AnalysisService calls KIS APIs in the analysis group.
type AnalysisService struct {
	executor rawapi.Executor
}

// Analysis returns the Analysis service.
func (c *Client) Analysis() AnalysisService {
	return AnalysisService{executor: c.rawAPIExecutor()}
}

// PsearchTitle calls the KIS 종목조건검색 목록조회[국내주식-038] API.
//
// KIS API: 종목조건검색 목록조회[국내주식-038]
// Summary: HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API입니다. 종목조건검색 목록조회 API(/uapi/domestic-stock/v1/quotations/psearch-title)의 output인 'seq'을 종목조건검색조회 API(/uapi/domestic-stock/v1/quotations/psearch-result)의 input으로 사용하시면 됩니다.  ※ 시스템 안정성을 위해 API로 제공되는 조건검색 결과의 경우 조건당 100건으로 제한을 둔 점 양해 부탁드립니다.  ※ [0110] 화면의 '대상변경' 설정사항은 HTS [0110] 사용자 조건검색 화면에만 적용됨에 유의 부탁드립니다.  ※ '조회가 계속 됩니다. (다음을 누르십시오.)' 오류 발생 시 해결방법 → HTS(efriend Plus) [0110] 조건검색 화면에서 조건을 등록하신 후, 왼쪽 하단의 "사용자조건 서버저장" 클릭하셔서 등록한 조건들을 서버로 보낸 후 다시 API 호출 시도 부탁드립니다.
// Operation ID: psearch-title
// Endpoint: GET /uapi/domestic-stock/v1/quotations/psearch-title
// TR ID: HHKST03900300
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) PsearchTitle(ctx context.Context, input PsearchTitleRequest) (PsearchTitleResponse, error) {
	return rawapi.PsearchTitle(ctx, s.executor, input)
}

// PsearchResult calls the KIS 종목조건검색조회 [국내주식-039] API.
//
// KIS API: 종목조건검색조회 [국내주식-039]
// Summary: HTS(efriend Plus) [0110] 조건검색에서 등록 및 서버저장한 나의 조건 목록을 확인할 수 있는 API입니다. 종목조건검색 목록조회 API(/uapi/domestic-stock/v1/quotations/psearch-title)의 output인 'seq'을 종목조건검색조회 API(/uapi/domestic-stock/v1/quotations/psearch-result)의 input으로 사용하시면 됩니다.  ※ 시스템 안정성을 위해 API로 제공되는 조건검색 결과의 경우 조건당 100건으로 제한을 둔 점 양해 부탁드립니다.  ※ [0110] 화면의 '대상변경' 설정사항은 HTS [0110] 사용자 조건검색 화면에만 적용됨에 유의 부탁드립니다.  ※ '조회가 계속 됩니다. (다음을 누르십시오.)' 오류 발생 시 해결방법 → HTS(efriend Plus) [0110] 조건검색 화면에서 조건을 등록하신 후, 왼쪽 하단의 "사용자조건 서버저장" 클릭하셔서 등록한 조건들을 서버로 보낸 후 다시 API 호출 시도 부탁드립니다.  ※ {"rt_cd":"1","msg_cd":"MCA05918","msg1":"종목코드 오류입니다."} 메시지 발생 이유 → 조건검색 결과 검색된 종목이 0개인 경우 위 응답값을 수신하게 됩니다.
// Operation ID: psearch-result
// Endpoint: GET /uapi/domestic-stock/v1/quotations/psearch-result
// TR ID: HHKST03900400
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) PsearchResult(ctx context.Context, input PsearchResultRequest) (PsearchResultResponse, error) {
	return rawapi.PsearchResult(ctx, s.executor, input)
}

// IntstockGrouplist calls the KIS 관심종목 그룹조회 [국내주식-204] API.
//
// KIS API: 관심종목 그룹조회 [국내주식-204]
// Summary: 관심종목 그룹조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0161] 관심종목 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ① 관심종목 그룹조회 → ② 관심종목 그룹별 종목조회 → ③ 관심종목(멀티종목) 시세조회 순서대로 호출하셔서 관심종목 시세 조회 가능합니다.  ※ 한 번의 호출에 최대 30종목의 시세 확인 가능합니다.  한국투자증권 Github 에서 관심종목 복수시세조회 파이썬 샘플코드를 참고하실 수 있습니다. https://github.com/koreainvestment/open-trading-api/blob/main/rest/get_interest_stocks_price.py
// Operation ID: intstock-grouplist
// Endpoint: GET /uapi/domestic-stock/v1/quotations/intstock-grouplist
// TR ID: HHKCM113004C7
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) IntstockGrouplist(ctx context.Context, input IntstockGrouplistRequest) (IntstockGrouplistResponse, error) {
	return rawapi.IntstockGrouplist(ctx, s.executor, input)
}

// IntstockMultprice calls the KIS 관심종목(멀티종목) 시세조회 [국내주식-205] API.
//
// KIS API: 관심종목(멀티종목) 시세조회 [국내주식-205]
// Summary: 관심종목(멀티종목) 시세조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0161] 관심종목 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: intstock-multprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/intstock-multprice
// TR ID: FHKST11300006
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) IntstockMultprice(ctx context.Context, input IntstockMultpriceRequest) (IntstockMultpriceResponse, error) {
	return rawapi.IntstockMultprice(ctx, s.executor, input)
}

// IntstockStocklistByGroup calls the KIS 관심종목 그룹별 종목조회 [국내주식-203] API.
//
// KIS API: 관심종목 그룹별 종목조회 [국내주식-203]
// Summary: 관심종목 그룹별 종목조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0161] 관심종목 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ① 관심종목 그룹조회 → ② 관심종목 그룹별 종목조회 → ③ 관심종목(멀티종목) 시세조회 순서대로 호출하셔서 관심종목 시세 조회 가능합니다.  ※ 한 번의 호출에 최대 30종목의 시세 확인 가능합니다.  한국투자증권 Github 에서 관심종목 복수시세조회 파이썬 샘플코드를 참고하실 수 있습니다. https://github.com/koreainvestment/open-trading-api/blob/main/rest/get_interest_stocks_price.py
// Operation ID: intstock-stocklist-by-group
// Endpoint: GET /uapi/domestic-stock/v1/quotations/intstock-stocklist-by-group
// TR ID: HHKCM113004C6
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) IntstockStocklistByGroup(ctx context.Context, input IntstockStocklistByGroupRequest) (IntstockStocklistByGroupResponse, error) {
	return rawapi.IntstockStocklistByGroup(ctx, s.executor, input)
}

// ForeignInstitutionTotal calls the KIS 국내기관_외국인 매매종목가집계[국내주식-037] API.
//
// KIS API: 국내기관_외국인 매매종목가집계[국내주식-037]
// Summary: 국내기관_외국인 매매종목가집계 API입니다.  HTS(efriend Plus) [0440] 외국인/기관 매매종목 가집계 화면을 API로 구현한 사항으로 화면을 함께 보시면 기능 이해가 쉽습니다.  증권사 직원이 장중에 집계/입력한 자료를 단순 누계한 수치로서,  입력시간은 외국인 09:30, 11:20, 13:20, 14:30 / 기관종합 10:00, 11:20, 13:20, 14:30 이며,  입력한 시간은 ±10분정도 차이가 발생할 수 있으며, 장운영 사정에 다라 변동될 수 있습니다.
// Operation ID: foreign-institution-total
// Endpoint: GET /uapi/domestic-stock/v1/quotations/foreign-institution-total
// TR ID: FHPTJ04400000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) ForeignInstitutionTotal(ctx context.Context, input ForeignInstitutionTotalRequest) (ForeignInstitutionTotalResponse, error) {
	return rawapi.ForeignInstitutionTotal(ctx, s.executor, input)
}

// FrgnmemTradeEstimate calls the KIS 외국계 매매종목 가집계 [국내주식-161] API.
//
// KIS API: 외국계 매매종목 가집계 [국내주식-161]
// Summary: 외국계 매매종목 가집계 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0430] 외국계 매매종목 가집계 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: frgnmem-trade-estimate
// Endpoint: GET /uapi/domestic-stock/v1/quotations/frgnmem-trade-estimate
// TR ID: FHKST644100C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) FrgnmemTradeEstimate(ctx context.Context, input FrgnmemTradeEstimateRequest) (FrgnmemTradeEstimateResponse, error) {
	return rawapi.FrgnmemTradeEstimate(ctx, s.executor, input)
}

// InvestorTradeByStockDaily calls the KIS 종목별 투자자매매동향(일별) API.
//
// KIS API: 종목별 투자자매매동향(일별)
// Summary: 국내주식 종목별 투자자매매동향(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0416] 종목별 일별동향 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 단위 : 금액(백만원) 수량(주)  당일 데이터는 15:40이후에 데이터가 가집계 및 산출되어 15:40부터 조회가능하며, 데이터 산출의 경우 산출 시간대는 일정하지 않을 수 있음을 참고 부탁드립니다. 추가로 API를 통한 00:00 ~ 15:40 이외의 시간은 당일 조회가 제한되는 점 이용에 참고 부탁드립니다.
// Operation ID: investor-trade-by-stock-daily
// Endpoint: GET /uapi/domestic-stock/v1/quotations/investor-trade-by-stock-daily
// TR ID: FHPTJ04160001
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InvestorTradeByStockDaily(ctx context.Context, input InvestorTradeByStockDailyRequest) (InvestorTradeByStockDailyResponse, error) {
	return rawapi.InvestorTradeByStockDaily(ctx, s.executor, input)
}

// InquireInvestorTimeByMarket calls the KIS 시장별 투자자매매동향(시세)[v1_국내주식-074] API.
//
// KIS API: 시장별 투자자매매동향(시세)[v1_국내주식-074]
// Summary: 시장별 투자자매매동향(시세성) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0403] 시장별 시간동향 의 상단 표 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-investor-time-by-market
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-investor-time-by-market
// TR ID: FHPTJ04030000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InquireInvestorTimeByMarket(ctx context.Context, input InquireInvestorTimeByMarketRequest) (InquireInvestorTimeByMarketResponse, error) {
	return rawapi.InquireInvestorTimeByMarket(ctx, s.executor, input)
}

// InquireInvestorDailyByMarket calls the KIS 시장별 투자자매매동향(일별) [국내주식-075] API.
//
// KIS API: 시장별 투자자매매동향(일별) [국내주식-075]
// Summary: 시장별 투자자매매동향(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0404] 시장별 일별동향 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-investor-daily-by-market
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-investor-daily-by-market
// TR ID: FHPTJ04040000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InquireInvestorDailyByMarket(ctx context.Context, input InquireInvestorDailyByMarketRequest) (InquireInvestorDailyByMarketResponse, error) {
	return rawapi.InquireInvestorDailyByMarket(ctx, s.executor, input)
}

// FrgnmemPchsTrend calls the KIS 종목별 외국계 순매수추이 [국내주식-164] API.
//
// KIS API: 종목별 외국계 순매수추이 [국내주식-164]
// Summary: 종목별 외국계 순매수추이 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0433] 종목별 외국계 순매수추이 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: frgnmem-pchs-trend
// Endpoint: GET /uapi/domestic-stock/v1/quotations/frgnmem-pchs-trend
// TR ID: FHKST644400C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) FrgnmemPchsTrend(ctx context.Context, input FrgnmemPchsTrendRequest) (FrgnmemPchsTrendResponse, error) {
	return rawapi.FrgnmemPchsTrend(ctx, s.executor, input)
}

// FrgnmemTradeTrend calls the KIS 회원사 실시간 매매동향(틱) [국내주식-163] API.
//
// KIS API: 회원사 실시간 매매동향(틱) [국내주식-163]
// Summary: 회원사 실시간 매매동향(틱) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0432] 회원사 실시간 매매동향 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  최근 100건까지 데이터 조회 가능합니다.
// Operation ID: frgnmem-trade-trend
// Endpoint: GET /uapi/domestic-stock/v1/quotations/frgnmem-trade-trend
// TR ID: FHPST04320000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) FrgnmemTradeTrend(ctx context.Context, input FrgnmemTradeTrendRequest) (FrgnmemTradeTrendResponse, error) {
	return rawapi.FrgnmemTradeTrend(ctx, s.executor, input)
}

// InquireMemberDaily calls the KIS 주식현재가 회원사 종목매매동향 [국내주식-197] API.
//
// KIS API: 주식현재가 회원사 종목매매동향 [국내주식-197]
// Summary: 주식현재가 회원사 종목매매동향 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0454] 증권사 종목매매동향 화면을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: inquire-member-daily
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-member-daily
// TR ID: FHPST04540000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InquireMemberDaily(ctx context.Context, input InquireMemberDailyRequest) (InquireMemberDailyResponse, error) {
	return rawapi.InquireMemberDaily(ctx, s.executor, input)
}

// ProgramTradeByStock calls the KIS 종목별 프로그램매매추이(체결)[v1_국내주식-044] API.
//
// KIS API: 종목별 프로그램매매추이(체결)[v1_국내주식-044]
// Summary: 국내주식 종목별 프로그램매매추이(체결) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0465] 종목별 프로그램 매매추이 화면(혹은 한국투자 MTS &gt; 국내 현재가 &gt; 기타수급 &gt; 프로그램) 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: program-trade-by-stock
// Endpoint: GET /uapi/domestic-stock/v1/quotations/program-trade-by-stock
// TR ID: FHPPG04650101
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) ProgramTradeByStock(ctx context.Context, input ProgramTradeByStockRequest) (ProgramTradeByStockResponse, error) {
	return rawapi.ProgramTradeByStock(ctx, s.executor, input)
}

// ProgramTradeByStockDaily calls the KIS 종목별 프로그램매매추이(일별) [국내주식-113] API.
//
// KIS API: 종목별 프로그램매매추이(일별) [국내주식-113]
// Summary: 국내주식 종목별 프로그램매매추이(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0465] 종목별 프로그램 매매추이 화면(혹은 한국투자 MTS &gt; 국내 현재가 &gt; 기타수급 &gt; 프로그램) 의 "일자별" 클릭 시 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: program-trade-by-stock-daily
// Endpoint: GET /uapi/domestic-stock/v1/quotations/program-trade-by-stock-daily
// TR ID: FHPPG04650201
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) ProgramTradeByStockDaily(ctx context.Context, input ProgramTradeByStockDailyRequest) (ProgramTradeByStockDailyResponse, error) {
	return rawapi.ProgramTradeByStockDaily(ctx, s.executor, input)
}

// InvestorTrendEstimate calls the KIS 종목별 외인기관 추정가집계[v1_국내주식-046] API.
//
// KIS API: 종목별 외인기관 추정가집계[v1_국내주식-046]
// Summary: 국내주식 종목별 외국인, 기관 추정가집계 API입니다.  한국투자 MTS &gt; 국내 현재가 &gt; 투자자 &gt; 투자자동향 탭 &gt; 왼쪽구분을 '추정(주)'로 선택 시 확인 가능한 데이터를 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  증권사 직원이 장중에 집계/입력한 자료를 단순 누계한 수치로서, 입력시간은 외국인 09:30, 11:20, 13:20, 14:30 / 기관종합 10:00, 11:20, 13:20, 14:30 이며, 사정에 따라 변동될 수 있습니다.
// Operation ID: investor-trend-estimate
// Endpoint: GET /uapi/domestic-stock/v1/quotations/investor-trend-estimate
// TR ID: HHPTJ04160200
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InvestorTrendEstimate(ctx context.Context, input InvestorTrendEstimateRequest) (InvestorTrendEstimateResponse, error) {
	return rawapi.InvestorTrendEstimate(ctx, s.executor, input)
}

// InquireDailyTradeVolume calls the KIS 종목별일별매수매도체결량 [v1_국내주식-056] API.
//
// KIS API: 종목별일별매수매도체결량 [v1_국내주식-056]
// Summary: 종목별일별매수매도체결량 API입니다. 실전계좌의 경우, 한 번의 호출에 최대 100건까지 확인 가능합니다. 국내주식 종목의 일별 매수체결량, 매도체결량 데이터를 확인할 수 있습니다.
// Operation ID: inquire-daily-trade-volume
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-daily-trade-volume
// TR ID: FHKST03010800
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InquireDailyTradeVolume(ctx context.Context, input InquireDailyTradeVolumeRequest) (InquireDailyTradeVolumeResponse, error) {
	return rawapi.InquireDailyTradeVolume(ctx, s.executor, input)
}

// CompProgramTradeToday calls the KIS 프로그램매매 종합현황(시간) [국내주식-114] API.
//
// KIS API: 프로그램매매 종합현황(시간) [국내주식-114]
// Summary: 프로그램매매 종합현황(시간) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0460] 프로그램매매 종합현황 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  ※ 장시간(09:00~15:30) 동안의 최근 30분간의 데이터 확인이 가능하며, 다음조회가 불가합니다. ※ 장시간(09:00~15:30) 이후에는 bsop_hour 에 153000 ~ 170000 까지의 시간데이터가 출력되지만 데이터는 모두 동일한 장마감 데이터인 점 유의 부탁드립니다.
// Operation ID: comp-program-trade-today
// Endpoint: GET /uapi/domestic-stock/v1/quotations/comp-program-trade-today
// TR ID: FHPPG04600101
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) CompProgramTradeToday(ctx context.Context, input CompProgramTradeTodayRequest) (CompProgramTradeTodayResponse, error) {
	return rawapi.CompProgramTradeToday(ctx, s.executor, input)
}

// CompProgramTradeDaily calls the KIS 프로그램매매 종합현황(일별)[국내주식-115] API.
//
// KIS API: 프로그램매매 종합현황(일별)[국내주식-115]
// Summary: 프로그램매매 종합현황(일별) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0460] 프로그램매매 종합현황 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  * 8개월 이상 과거 조회는 불가하며 에러메시지가 발생합니다.
// Operation ID: comp-program-trade-daily
// Endpoint: GET /uapi/domestic-stock/v1/quotations/comp-program-trade-daily
// TR ID: FHPPG04600001
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) CompProgramTradeDaily(ctx context.Context, input CompProgramTradeDailyRequest) (CompProgramTradeDailyResponse, error) {
	return rawapi.CompProgramTradeDaily(ctx, s.executor, input)
}

// InvestorProgramTradeToday calls the KIS 프로그램매매 투자자매매동향(당일) [국내주식-116] API.
//
// KIS API: 프로그램매매 투자자매매동향(당일) [국내주식-116]
// Summary: 프로그램매매 투자자매매동향(당일) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0466] 프로그램매매 투자자별 동향 화면 의 "당일동향" 표의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: investor-program-trade-today
// Endpoint: GET /uapi/domestic-stock/v1/quotations/investor-program-trade-today
// TR ID: HHPPG046600C1
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) InvestorProgramTradeToday(ctx context.Context, input InvestorProgramTradeTodayRequest) (InvestorProgramTradeTodayResponse, error) {
	return rawapi.InvestorProgramTradeToday(ctx, s.executor, input)
}

// DailyCreditBalance calls the KIS 국내주식 신용잔고 일별추이[국내주식-110] API.
//
// KIS API: 국내주식 신용잔고 일별추이[국내주식-110]
// Summary: 국내주식 신용잔고 일별추이 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0476] 국내주식 신용잔고 일별추이 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 한 번의 호출에 최대 30건 확인 가능하며, fid_input_date_1 을 입력하여 다음 조회가 가능합니다.  ※ 상환수량은 "매도상환수량+현금상환수량"의 합계 수치입니다.
// Operation ID: daily-credit-balance
// Endpoint: GET /uapi/domestic-stock/v1/quotations/daily-credit-balance
// TR ID: FHPST04760000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) DailyCreditBalance(ctx context.Context, input DailyCreditBalanceRequest) (DailyCreditBalanceResponse, error) {
	return rawapi.DailyCreditBalance(ctx, s.executor, input)
}

// ExpPriceTrend calls the KIS 국내주식 예상체결가 추이[국내주식-118] API.
//
// KIS API: 국내주식 예상체결가 추이[국내주식-118]
// Summary: 국내주식 예상체결가 추이 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0184] 예상체결지수 추이 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 최대 30건 확인 가능하며, 다음 조회가 불가합니다.
// Operation ID: exp-price-trend
// Endpoint: GET /uapi/domestic-stock/v1/quotations/exp-price-trend
// TR ID: FHPST01810000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) ExpPriceTrend(ctx context.Context, input ExpPriceTrendRequest) (ExpPriceTrendResponse, error) {
	return rawapi.ExpPriceTrend(ctx, s.executor, input)
}

// DailyShortSale calls the KIS 국내주식 공매도 일별추이[국내주식-134] API.
//
// KIS API: 국내주식 공매도 일별추이[국내주식-134]
// Summary:
// Operation ID: daily-short-sale
// Endpoint: GET /uapi/domestic-stock/v1/quotations/daily-short-sale
// TR ID: FHPST04830000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) DailyShortSale(ctx context.Context, input DailyShortSaleRequest) (DailyShortSaleResponse, error) {
	return rawapi.DailyShortSale(ctx, s.executor, input)
}

// OvertimeExpTransFluct calls the KIS 국내주식 시간외예상체결등락률 [국내주식-140] API.
//
// KIS API: 국내주식 시간외예상체결등락률 [국내주식-140]
// Summary: 국내주식 시간외예상체결등락률 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0236] 시간외 예상체결등락률 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: overtime-exp-trans-fluct
// Endpoint: GET /uapi/domestic-stock/v1/ranking/overtime-exp-trans-fluct
// TR ID: FHKST11860000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) OvertimeExpTransFluct(ctx context.Context, input OvertimeExpTransFluctRequest) (OvertimeExpTransFluctResponse, error) {
	return rawapi.OvertimeExpTransFluct(ctx, s.executor, input)
}

// TradprtByamt calls the KIS 국내주식 체결금액별 매매비중 [국내주식-192] API.
//
// KIS API: 국내주식 체결금액별 매매비중 [국내주식-192]
// Summary: 국내주식 체결금액별 매매비중 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0135] 체결금액별 매매비중 화면의 "상단 표" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: tradprt-byamt
// Endpoint: GET /uapi/domestic-stock/v1/quotations/tradprt-byamt
// TR ID: FHKST111900C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) TradprtByamt(ctx context.Context, input TradprtByamtRequest) (TradprtByamtResponse, error) {
	return rawapi.TradprtByamt(ctx, s.executor, input)
}

// Mktfunds calls the KIS 국내 증시자금 종합 [국내주식-193] API.
//
// KIS API: 국내 증시자금 종합 [국내주식-193]
// Summary: 국내 증시자금 종합 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0470] 증시자금 종합 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. (단위: 억원)  ※ 해당자료는 금융투자협회의 자료를 제공하고 있으며, 오류와 지연이 발생할 수 있습니다. ※ 위 정보에 의한 투자판단의 최종책임은 정보이용자에게 있으며, 당사와 한국금융투자협회는 어떠한 법적인 책임도 지지 않사오니 투자에 참고로만 이용하시기 바랍니다.
// Operation ID: mktfunds
// Endpoint: GET /uapi/domestic-stock/v1/quotations/mktfunds
// TR ID: FHKST649100C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) Mktfunds(ctx context.Context, input MktfundsRequest) (MktfundsResponse, error) {
	return rawapi.Mktfunds(ctx, s.executor, input)
}

// DailyLoanTrans calls the KIS 종목별 일별 대차거래추이 [국내주식-135] API.
//
// KIS API: 종목별 일별 대차거래추이 [국내주식-135]
// Summary: 종목별 일별 대차거래추이 API입니다. 한 번의 조회에 최대 100건까지 조회 가능하며, start_date, end_date 를 수정하여 다음 조회가 가능합니다.
// Operation ID: daily-loan-trans
// Endpoint: GET /uapi/domestic-stock/v1/quotations/daily-loan-trans
// TR ID: HHPST074500C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) DailyLoanTrans(ctx context.Context, input DailyLoanTransRequest) (DailyLoanTransResponse, error) {
	return rawapi.DailyLoanTrans(ctx, s.executor, input)
}

// CaptureUplowprice calls the KIS 국내주식 상하한가 포착 [국내주식-190] API.
//
// KIS API: 국내주식 상하한가 포착 [국내주식-190]
// Summary: 국내주식 상하한가 포착 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0917] 실시간 상하한가 포착 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: capture-uplowprice
// Endpoint: GET /uapi/domestic-stock/v1/quotations/capture-uplowprice
// TR ID: FHKST130000C0
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) CaptureUplowprice(ctx context.Context, input CaptureUplowpriceRequest) (CaptureUplowpriceResponse, error) {
	return rawapi.CaptureUplowprice(ctx, s.executor, input)
}

// PbarTratio calls the KIS 국내주식 매물대/거래비중 [국내주식-196] API.
//
// KIS API: 국내주식 매물대/거래비중 [국내주식-196]
// Summary: 국내주식 매물대/거래비중 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0113] 당일가격대별 매물대 화면의 데이터 중 일부를 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: pbar-tratio
// Endpoint: GET /uapi/domestic-stock/v1/quotations/pbar-tratio
// TR ID: FHPST01130000
// Virtual TR ID: 모의투자 미지원
// Role hint: market_scan
func (s AnalysisService) PbarTratio(ctx context.Context, input PbarTratioRequest) (PbarTratioResponse, error) {
	return rawapi.PbarTratio(ctx, s.executor, input)
}
