// Code generated by clients/kis/internal/codegen/kisopenapi; DO NOT EDIT.

package kis

import (
	"context"

	"github.com/ev3rlit/mwosa/clients/kis/internal/generated/rawapi"
)

// ELWQuoteService calls KIS APIs in the elw-quote group.
type ELWQuoteService struct {
	executor rawapi.Executor
}

// ELWQuote returns the ELWQuote service.
func (c *Client) ELWQuote() ELWQuoteService {
	return ELWQuoteService{executor: c.rawAPIExecutor()}
}

// InquireELWPrice calls the KIS ELW 현재가 시세[v1_국내주식-014] API.
//
// KIS API: ELW 현재가 시세[v1_국내주식-014]
// Summary: ELW 현재가 시세 API입니다. ELW 관련 정보를 얻을 수 있습니다.
// Operation ID: inquire-elw-price
// Endpoint: GET /uapi/domestic-stock/v1/quotations/inquire-elw-price
// TR ID: FHKEW15010000
// Virtual TR ID: FHKEW15010000
// Role hint: read_only
func (s ELWQuoteService) InquireELWPrice(ctx context.Context, input InquireELWPriceRequest) (InquireELWPriceResponse, error) {
	return rawapi.InquireELWPrice(ctx, s.executor, input)
}

// NewlyListed calls the KIS ELW 신규상장종목 [국내주식-181] API.
//
// KIS API: ELW 신규상장종목 [국내주식-181]
// Summary: ELW 신규상장종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0297] ELW 신규상장종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: newly-listed
// Endpoint: GET /uapi/elw/v1/quotations/newly-listed
// TR ID: FHKEW154800C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) NewlyListed(ctx context.Context, input NewlyListedRequest) (NewlyListedResponse, error) {
	return rawapi.NewlyListed(ctx, s.executor, input)
}

// Sensitivity calls the KIS ELW 민감도 순위[국내주식-170] API.
//
// KIS API: ELW 민감도 순위[국내주식-170]
// Summary: ELW 민감도 순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0285] ELW 민감도 순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: sensitivity
// Endpoint: GET /uapi/elw/v1/ranking/sensitivity
// TR ID: FHPEW02850000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) Sensitivity(ctx context.Context, input SensitivityRequest) (SensitivityResponse, error) {
	return rawapi.Sensitivity(ctx, s.executor, input)
}

// UdrlAssetPrice calls the KIS ELW 기초자산별 종목시세 [국내주식-186] API.
//
// KIS API: ELW 기초자산별 종목시세 [국내주식-186]
// Summary: ELW 기초자산별 종목시세  API입니다. 한국투자 HTS(eFriend Plus) &gt; [0288] ELW 기초자산별 ELW 시세 화면의 "우측 기초자산별 종목 리스트" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: udrl-asset-price
// Endpoint: GET /uapi/elw/v1/quotations/udrl-asset-price
// TR ID: FHKEW154101C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) UdrlAssetPrice(ctx context.Context, input UdrlAssetPriceRequest) (UdrlAssetPriceResponse, error) {
	return rawapi.UdrlAssetPrice(ctx, s.executor, input)
}

// CondSearch calls the KIS ELW 종목검색 [국내주식-166] API.
//
// KIS API: ELW 종목검색 [국내주식-166]
// Summary: ELW 종목검색 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0291] ELW 종목검색 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다. 한 번의 호출에 최대 100건까지 확인 가능합니다.
// Operation ID: cond-search
// Endpoint: GET /uapi/elw/v1/quotations/cond-search
// TR ID: FHKEW15100000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) CondSearch(ctx context.Context, input CondSearchRequest) (CondSearchResponse, error) {
	return rawapi.CondSearch(ctx, s.executor, input)
}

// QuickChange calls the KIS ELW 당일급변종목[국내주식-171] API.
//
// KIS API: ELW 당일급변종목[국내주식-171]
// Summary: ELW 당일급변종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0287] ELW 당일급변종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: quick-change
// Endpoint: GET /uapi/elw/v1/ranking/quick-change
// TR ID: FHPEW02870000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) QuickChange(ctx context.Context, input QuickChangeRequest) (QuickChangeResponse, error) {
	return rawapi.QuickChange(ctx, s.executor, input)
}

// UdrlAssetList calls the KIS ELW 기초자산 목록조회 [국내주식-185] API.
//
// KIS API: ELW 기초자산 목록조회 [국내주식-185]
// Summary: ELW 기초자산 목록조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0288] ELW 기초자산별 ELW 시세 화면 의 "왼쪽 기초자산 목록" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: udrl-asset-list
// Endpoint: GET /uapi/elw/v1/quotations/udrl-asset-list
// TR ID: FHKEW154100C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) UdrlAssetList(ctx context.Context, input UdrlAssetListRequest) (UdrlAssetListResponse, error) {
	return rawapi.UdrlAssetList(ctx, s.executor, input)
}

// CompareStocks calls the KIS ELW 비교대상종목조회 [국내주식-183] API.
//
// KIS API: ELW 비교대상종목조회 [국내주식-183]
// Summary: ELW 비교대상종목조회 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0288] ELW 기초자산별 ELW 시세의 좌측 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: compare-stocks
// Endpoint: GET /uapi/elw/v1/quotations/compare-stocks
// TR ID: FHKEW151701C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) CompareStocks(ctx context.Context, input CompareStocksRequest) (CompareStocksResponse, error) {
	return rawapi.CompareStocks(ctx, s.executor, input)
}

// LpTradeTrend calls the KIS ELW LP매매추이 [국내주식-182] API.
//
// KIS API: ELW LP매매추이 [국내주식-182]
// Summary: ELW LP매매추이 API입니다. 한국투자 HTS(eFriend Plus) &gt; [0376] ELW LP매매추이 화면 의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: lp-trade-trend
// Endpoint: GET /uapi/elw/v1/quotations/lp-trade-trend
// TR ID: FHPEW03760000
// Virtual TR ID:
// Role hint: read_only
func (s ELWQuoteService) LpTradeTrend(ctx context.Context, input LpTradeTrendRequest) (LpTradeTrendResponse, error) {
	return rawapi.LpTradeTrend(ctx, s.executor, input)
}

// IndicatorTrendCcnl calls the KIS ELW 투자지표추이(체결) [국내주식-172] API.
//
// KIS API: ELW 투자지표추이(체결) [국내주식-172]
// Summary: ELW 투자지표추이(체결) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0274] ELW 투자지표추이 화면에서 "시간별 비교추이" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: indicator-trend-ccnl
// Endpoint: GET /uapi/elw/v1/quotations/indicator-trend-ccnl
// TR ID: FHPEW02740100
// Virtual TR ID: 모의투자 미지원
// Role hint: trades
func (s ELWQuoteService) IndicatorTrendCcnl(ctx context.Context, input IndicatorTrendCcnlRequest) (IndicatorTrendCcnlResponse, error) {
	return rawapi.IndicatorTrendCcnl(ctx, s.executor, input)
}

// IndicatorTrendMinute calls the KIS ELW 투자지표추이(분별) [국내주식-174] API.
//
// KIS API: ELW 투자지표추이(분별) [국내주식-174]
// Summary: ELW 투자지표추이(분별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0274] ELW 투자지표추이 화면 데이터의 "분별 비교추이" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: indicator-trend-minute
// Endpoint: GET /uapi/elw/v1/quotations/indicator-trend-minute
// TR ID: FHPEW02740300
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) IndicatorTrendMinute(ctx context.Context, input IndicatorTrendMinuteRequest) (IndicatorTrendMinuteResponse, error) {
	return rawapi.IndicatorTrendMinute(ctx, s.executor, input)
}

// IndicatorTrendDaily calls the KIS ELW 투자지표추이(일별) [국내주식-173] API.
//
// KIS API: ELW 투자지표추이(일별) [국내주식-173]
// Summary: ELW 투자지표추이(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0274] ELW 투자지표추이 화면에서 "일자별 비교추이" 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: indicator-trend-daily
// Endpoint: GET /uapi/elw/v1/quotations/indicator-trend-daily
// TR ID: FHPEW02740200
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) IndicatorTrendDaily(ctx context.Context, input IndicatorTrendDailyRequest) (IndicatorTrendDailyResponse, error) {
	return rawapi.IndicatorTrendDaily(ctx, s.executor, input)
}

// VolatilityTrendTick calls the KIS ELW 변동성 추이(틱) [국내주식-180] API.
//
// KIS API: ELW 변동성 추이(틱) [국내주식-180]
// Summary: ELW 변동성 추이(틱) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0284] ELW 변동성 추이 화면의 "틱 차트" 변동성 추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: volatility-trend-tick
// Endpoint: GET /uapi/elw/v1/quotations/volatility-trend-tick
// TR ID: FHPEW02840400
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) VolatilityTrendTick(ctx context.Context, input VolatilityTrendTickRequest) (VolatilityTrendTickResponse, error) {
	return rawapi.VolatilityTrendTick(ctx, s.executor, input)
}

// VolatilityTrendCcnl calls the KIS ELW 변동성추이(체결) [국내주식-177] API.
//
// KIS API: ELW 변동성추이(체결) [국내주식-177]
// Summary: ELW 변동성 추이(체결) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0284] ELW 변동성 추이 화면의 "시간별" 변동성 추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: volatility-trend-ccnl
// Endpoint: GET /uapi/elw/v1/quotations/volatility-trend-ccnl
// TR ID: FHPEW02840100
// Virtual TR ID: 모의투자 미지원
// Role hint: trades
func (s ELWQuoteService) VolatilityTrendCcnl(ctx context.Context, input VolatilityTrendCcnlRequest) (VolatilityTrendCcnlResponse, error) {
	return rawapi.VolatilityTrendCcnl(ctx, s.executor, input)
}

// VolatilityTrendDaily calls the KIS ELW 변동성 추이(일별) [국내주식-178] API.
//
// KIS API: ELW 변동성 추이(일별) [국내주식-178]
// Summary: ELW 변동성 추이(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0284] ELW 변동성 추이 화면의 "일별" 변동성 추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: volatility-trend-daily
// Endpoint: GET /uapi/elw/v1/quotations/volatility-trend-daily
// TR ID: FHPEW02840200
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) VolatilityTrendDaily(ctx context.Context, input VolatilityTrendDailyRequest) (VolatilityTrendDailyResponse, error) {
	return rawapi.VolatilityTrendDaily(ctx, s.executor, input)
}

// SensitivityTrendCcnl calls the KIS ELW 민감도 추이(체결) [국내주식-175] API.
//
// KIS API: ELW 민감도 추이(체결) [국내주식-175]
// Summary: ELW 민감도 추이(체결) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0283] ELW 민감도 추이 화면 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: sensitivity-trend-ccnl
// Endpoint: GET /uapi/elw/v1/quotations/sensitivity-trend-ccnl
// TR ID: FHPEW02830100
// Virtual TR ID: 모의투자 미지원
// Role hint: trades
func (s ELWQuoteService) SensitivityTrendCcnl(ctx context.Context, input SensitivityTrendCcnlRequest) (SensitivityTrendCcnlResponse, error) {
	return rawapi.SensitivityTrendCcnl(ctx, s.executor, input)
}

// VolatilityTrendMinute calls the KIS ELW 변동성 추이(분별) [국내주식-179] API.
//
// KIS API: ELW 변동성 추이(분별) [국내주식-179]
// Summary: ELW 변동성 추이(분별) API입니다.  한국투자 HTS(eFriend Plus) &gt; [0284] ELW 변동성 추이 화면의 "분별" 변동성 추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: volatility-trend-minute
// Endpoint: GET /uapi/elw/v1/quotations/volatility-trend-minute
// TR ID: FHPEW02840300
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) VolatilityTrendMinute(ctx context.Context, input VolatilityTrendMinuteRequest) (VolatilityTrendMinuteResponse, error) {
	return rawapi.VolatilityTrendMinute(ctx, s.executor, input)
}

// SensitivityTrendDaily calls the KIS ELW 민감도 추이(일별) [국내주식-176] API.
//
// KIS API: ELW 민감도 추이(일별) [국내주식-176]
// Summary: ELW 민감도 추이(일별) API입니다. 한국투자 HTS(eFriend Plus) &gt; [0283] ELW 민감도 추이 화면의 "일자별" 민감도추이 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: sensitivity-trend-daily
// Endpoint: GET /uapi/elw/v1/quotations/sensitivity-trend-daily
// TR ID: FHPEW02830200
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) SensitivityTrendDaily(ctx context.Context, input SensitivityTrendDailyRequest) (SensitivityTrendDailyResponse, error) {
	return rawapi.SensitivityTrendDaily(ctx, s.executor, input)
}

// ExpirationStocks calls the KIS ELW 만기예정/만기종목 [국내주식-184] API.
//
// KIS API: ELW 만기예정/만기종목 [국내주식-184]
// Summary: ELW 만기예정/만기종목 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0290] ELW 만기예정/만기종목 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.  최근 100건까지 데이터 조회 가능합니다.
// Operation ID: expiration-stocks
// Endpoint: GET /uapi/elw/v1/quotations/expiration-stocks
// TR ID: FHKEW154700C0
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) ExpirationStocks(ctx context.Context, input ExpirationStocksRequest) (ExpirationStocksResponse, error) {
	return rawapi.ExpirationStocks(ctx, s.executor, input)
}

// Indicator calls the KIS ELW 지표순위[국내주식-169] API.
//
// KIS API: ELW 지표순위[국내주식-169]
// Summary: ELW 지표순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0279] ELW 지표순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: indicator
// Endpoint: GET /uapi/elw/v1/ranking/indicator
// TR ID: FHPEW02790000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) Indicator(ctx context.Context, input IndicatorRequest) (IndicatorResponse, error) {
	return rawapi.Indicator(ctx, s.executor, input)
}

// UpdownRate calls the KIS ELW 상승률순위[국내주식-167] API.
//
// KIS API: ELW 상승률순위[국내주식-167]
// Summary: ELW 상승률순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0277] ELW 상승률순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: updown-rate
// Endpoint: GET /uapi/elw/v1/ranking/updown-rate
// TR ID: FHPEW02770000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) UpdownRate(ctx context.Context, input UpdownRateRequest) (UpdownRateResponse, error) {
	return rawapi.UpdownRate(ctx, s.executor, input)
}

// ELWRankingVolumeRank calls the KIS ELW 거래량순위[국내주식-168] API.
//
// KIS API: ELW 거래량순위[국내주식-168]
// Summary: ELW 거래량순위 API입니다.  한국투자 HTS(eFriend Plus) &gt; [0278] ELW 거래량순위 화면의 기능을 API로 개발한 사항으로, 해당 화면을 참고하시면 기능을 이해하기 쉽습니다.
// Operation ID: elw-ranking-volume-rank
// Endpoint: GET /uapi/elw/v1/ranking/volume-rank
// TR ID: FHPEW02780000
// Virtual TR ID: 모의투자 미지원
// Role hint: read_only
func (s ELWQuoteService) ELWRankingVolumeRank(ctx context.Context, input ELWRankingVolumeRankRequest) (ELWRankingVolumeRankResponse, error) {
	return rawapi.ELWRankingVolumeRank(ctx, s.executor, input)
}
